workflows:
  ios-workflow:
    name: iOS Build and Deploy
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_VERSION: "15.0"
        FLUTTER_VERSION: "3.35.3"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # 从App Store Connect获取
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # 从App Store Connect获取
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # 从App Store Connect获取
        CERTIFICATE_PRIVATE_KEY: Encrypted(...) # iOS开发证书私钥
        BUNDLE_ID: "com.pjpc.school.pjpcAppFlutter"
        APP_STORE_APP_ID: Encrypted(...) # App Store应用ID
        APP_STORE_CONNECT_TEAM_ID: Encrypted(...) # 团队ID
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
