workflows:
  ios-workflow:
    name: iOS Build for AltStore
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_VERSION: "15.0"
        FLUTTER_VERSION: "3.35.3"
        BUNDLE_ID: "com.pjpc.school.pjpcAppFlutter"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build ipa for AltStore
        script: |
          flutter build ipa --release --no-codesign \
            --build-name=1.0.0 \
            --build-number=1
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
