"use client"

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react"

export type Language = "zh" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // AppShell
    "app.title": "安亲班管理系统",
    "app.subtitle": "专业的安亲班教育管理解决方案",
    "nav.dashboard": "概览",
    "nav.slideshow": "幻灯片",
    "nav.tv_board": "TV看板",
    "nav.education": "教务",
    "nav.students": "学生列表",
    "nav.student_reports": "学生报告",
    "nav.parents": "家长管理",
    "nav.homework": "作业管理",
    "nav.grades": "成绩管理",
    "nav.pickup": "接送管理",
    "nav.daily_logs": "每日日志",
    "nav.resource_library": "资源库",
    "nav.teachers": "教师列表",
    "nav.teacher_attendance": "教师考勤",
    "nav.courses": "课程管理",
    "nav.finance": "财务",
    "nav.finance_overview": "财务概览",
    "nav.fees": "收费管理",
    "nav.student_fees": "学生费用",
    "nav.invoices": "发票管理",
    "nav.payments": "付款管理",
    "nav.receipts": "收据管理",
    "nav.payroll": "薪资管理",
    "nav.expenses": "支出管理",
    "nav.bank_reconciliation": "银行对账",
    "nav.budget": "预算管理",
    "nav.financial_reports": "财务报表",
    "nav.inventory": "库存管理",
    "nav.system": "系统",
    "nav.attendance": "考勤中心",
    "nav.card_management": "卡片管理",
    "nav.points": "积分操作",
    "nav.points_rules": "积分规则",
    "nav.points_leaderboard": "积分排行",
    "nav.user_management": "用户管理",
    "nav.center_management": "分行管理",
    "nav.settings": "系统设置",
    "nav.admin_panel": "管理面板",
    "nav.teacher_workspace": "我的工作台",
    "nav.student_checkin": "学生签到",
    "nav.parent_portal": "家长门户",
    "nav.parent_dashboard": "孩子总览",
    "nav.parent_daily_logs": "每日日志",
    "nav.parent_grades": "成绩查询",
    "nav.parent_payments": "缴费记录",
    "nav.parent_attendance": "出勤记录",
    "nav.parent_notifications": "通知消息",
    "nav.accountant_workspace": "财务工作台",
    "nav.center_filter": "分行筛选",
    "nav.all_centers": "全部",
    "nav.edit_nav": "调整菜单顺序",
    "nav.finish_sort": "完成排序",
    "nav.reset_default": "恢复默认",
    "nav.online": "在线",
    "nav.login": "登入",
    "nav.logout": "退出",
    "nav.notifications": "通知",
    "role.admin": "管理员",
    "role.teacher": "教师",
    "role.parent": "家长",
    "role.accountant": "会计",
    // Login page
    "login.title": "安亲班管理系统",
    "login.subtitle": "请登录您的账户",
    "login.card_title": "用户登录",
    "login.features": "系统功能",
    "login.feature_students": "学生管理",
    "login.feature_attendance": "考勤打卡",
    "login.feature_courses": "课程排班",
    "login.feature_points": "积分奖励",
    // Breadcrumbs
    "breadcrumb.dashboard": "仪表板",
    "breadcrumb.slideshow": "幻灯片",
    "breadcrumb.education_overview": "教育概览",
    "breadcrumb.student_list": "学生列表",
    "breadcrumb.student_reports": "学生报告",
    "breadcrumb.daily_logs": "每日日志",
    "breadcrumb.grades": "成绩管理",
    "breadcrumb.pickup": "接送管理",
    "breadcrumb.parents": "家长管理",
    "breadcrumb.homework": "作业管理",
    "breadcrumb.teachers": "教师列表",
    "breadcrumb.teacher_attendance": "教师考勤",
    "breadcrumb.courses": "课程管理",
    "breadcrumb.finance_overview": "财务概览",
    "breadcrumb.fees": "收费管理",
    "breadcrumb.student_fees": "学生费用",
    "breadcrumb.invoices": "发票管理",
    "breadcrumb.payments": "付款管理",
    "breadcrumb.receipts": "收据管理",
    "breadcrumb.payroll": "薪资管理",
    "breadcrumb.expenses": "支出管理",
    "breadcrumb.bank": "银行对账",
    "breadcrumb.budget": "预算管理",
    "breadcrumb.financial_reports": "财务报表",
    "breadcrumb.inventory": "库存管理",
    "breadcrumb.attendance": "考勤中心",
    "breadcrumb.card_management": "卡片管理",
    "breadcrumb.points": "积分操作",
    "breadcrumb.points_rules": "积分规则",
    "breadcrumb.points_leaderboard": "积分排行",
    "breadcrumb.user_management": "用户管理",
    "breadcrumb.center_management": "分行管理",
    "breadcrumb.settings": "系统设置",
    "breadcrumb.report_detail": "报告详情",
    "breadcrumb.loading": "加载中...",
    "breadcrumb.unknown": "未知",
  
    "admin.accountant": "会计",
    "admin.add": "添加",
    "admin.add_role": "新增角色",
    "admin.admin": "管理员",
    "admin.approved": "已批准",
    "admin.bank_reconciliation": "银行对账",
    "admin.budget_management": "预算管理",
    "admin.card_management": "卡片管理",
    "admin.course_management": "课程管理",
    "admin.create_failed": "创建失败",
    "admin.daily_logs": "每日日志",
    "admin.dashboard": "仪表板",
    "admin.description": "描述",
    "admin.expense_management": "支出管理",
    "admin.fee_management": "收费管理",
    "admin.finance_management": "财务管理",
    "admin.finance_overview": "财务概览",
    "admin.financial_report": "财务报表",
    "admin.grade_management": "成绩管理",
    "admin.insufficient_permissions": "权限不足",
    "admin.inventory_management": "库存管理",
    "admin.loading...": "加载中...",
    "admin.network_error": "网络错误",
    "admin.no_users": "暂无用户",
    "admin.parent": "家长",
    "admin.payroll_management": "薪资管理",
    "admin.pending_review": "待审核",
    "admin.pickup_management": "接送管理",
    "admin.points": "积分操作",
    "admin.points_records": "积分记录",
    "admin.rejected": "已拒绝",
    "admin.reviewed": "已审核",
    "admin.role": "角色",
    "admin.student_list": "学生列表",
    "admin.student_management": "学生管理",
    "admin.system_settings": "系统设置",
    "admin.teacher": "教师",
    "admin.teacher_list": "教师列表",
    "admin.teacher_management": "教师管理",
    "admin.timetable": "课程表",
    "admin.update": "更新",
    "admin.user_management": "用户管理",
    "attendance.absent": "缺勤",
    "attendance.actions": "操作",
    "attendance.add": "添加",
    "attendance.add_course": "添加课程",
    "attendance.all": "全部",
    "attendance.all_centers": "全部中心",
    "attendance.all_status": "全部状态",
    "attendance.all_types": "全部类型",
    "attendance.approved": "已批准",
    "attendance.attendance_management": "考勤管理",
    "attendance.attendance_rate": "出勤率",
    "attendance.attendance_records": "出勤记录",
    "attendance.branch": "分校",
    "attendance.cancelled": "已取消",
    "attendance.center": "中心",
    "attendance.check_in": "签到",
    "attendance.check_in_time": "签到时间",
    "attendance.check_out": "签退",
    "attendance.check_out_time": "签退时间",
    "attendance.checked_in": "已签到",
    "attendance.checked_in_count": "签到人数",
    "attendance.checked_out": "已签退",
    "attendance.chinese": "华文",
    "attendance.completed": "已完成",
    "attendance.confirmed": "已确认",
    "attendance.course_name": "课程名称",
    "attendance.course_scheduling": "课程排班",
    "attendance.date": "日期",
    "attendance.days": "天",
    "attendance.description": "描述",
    "attendance.disable": "禁用",
    "attendance.early_leave": "早退",
    "attendance.enable": "启用",
    "attendance.end_time": "结束时间",
    "attendance.english": "英文",
    "attendance.failed": "失败",
    "attendance.form_1": "中一",
    "attendance.form_2": "中二",
    "attendance.form_3": "中三",
    "attendance.friday": "周五",
    "attendance.grade": "年级",
    "attendance.hours": "小时",
    "attendance.in_progress": "进行中",
    "attendance.late": "迟到",
    "attendance.load_failed": "加载失败",
    "attendance.loading...": "加载中...",
    "attendance.mathematics": "数学",
    "attendance.monday": "周一",
    "attendance.name": "姓名",
    "attendance.nfc": "NFC",
    "attendance.no_data": "暂无数据",
    "attendance.notes": "备注",
    "attendance.offline": "离线",
    "attendance.online": "在线",
    "attendance.operation_failed": "操作失败",
    "attendance.present": "出勤",
    "attendance.rejected": "已拒绝",
    "attendance.saturday": "周六",
    "attendance.save_failed": "保存失败",
    "attendance.scheduled": "已安排",
    "attendance.science": "科学",
    "attendance.search_students": "搜索学生",
    "attendance.select_subject": "选择科目",
    "attendance.select_teacher": "选择教师",
    "attendance.start_time": "开始时间",
    "attendance.status": "状态",
    "attendance.student": "学生",
    "attendance.student_name": "学生姓名",
    "attendance.subject": "科目",
    "attendance.success": "成功",
    "attendance.sunday": "周日",
    "attendance.teacher": "教师",
    "attendance.thursday": "周四",
    "attendance.time": "时间",
    "attendance.time_range": "时间范围",
    "attendance.today": "今天",
    "attendance.today's_attendance": "今日考勤",
    "attendance.total_people": "总人数",
    "attendance.tuesday": "周二",
    "attendance.type": "类型",
    "attendance.under_maintenance": "维护中",
    "attendance.unknown": "未知",
    "attendance.wednesday": "周三",
    "attendance.weekend": "周末",
    "attendance.workday": "工作日",
    "attendance.year": "年份",
    "attendance.year_1": "一年级",
    "attendance.year_2": "二年级",
    "attendance.year_3": "三年级",
    "attendance.year_4": "四年级",
    "attendance.year_5": "五年级",
    "attendance.year_6": "六年级",
    "auth.accountant": "会计",
    "auth.admin": "管理员",
    "auth.after_school_care_management_system": "安亲班管理系统",
    "auth.confirm_password": "确认密码",
    "auth.email_address": "邮箱地址",
    "auth.enter_password": "请输入密码",
    "auth.login": "登录",
    "auth.name": "姓名",
    "auth.parent": "家长",
    "auth.password": "密码",
    "auth.register": "注册",
    "auth.reset_password": "重置密码",
    "card.actions": "操作",
    "card.active": "活跃",
    "card.add": "添加",
    "card.balance": "余额",
    "card.card_status": "卡片状态",
    "card.card_type": "卡片类型",
    "card.check_in": "签到",
    "card.check_out": "签退",
    "card.data_sync": "数据同步",
    "card.disabled": "停用",
    "card.edit_card": "编辑卡片",
    "card.lost": "丢失",
    "card.nfc": "NFC",
    "card.normal": "正常",
    "card.not_set": "未设置",
    "card.notes": "备注",
    "card.processing...": "处理中...",
    "card.status": "状态",
    "card.student": "学生",
    "card.student_name": "学生姓名",
    "card.teacher": "教师",
    "card.update": "更新",
    "common.account_number": "账户号码",
    "common.accountant": "会计",
    "common.actions": "操作",
    "common.active": "活跃",
    "common.add_card": "添加卡片",
    "common.address": "地址",
    "common.admin": "管理员",
    "common.admin_panel": "管理面板",
    "common.advanced_filters": "高级筛选",
    "common.all": "全部",
    "common.all_courses": "全部课程",
    "common.all_parents": "全体家长",
    "common.all_status": "全部状态",
    "common.all_subjects": "全部科目",
    "common.all_teachers": "全部教师",
    "common.all_types": "全部类型",
    "common.amount": "金额",
    "common.analyzing...": "分析中...",
    "common.approved": "已批准",
    "common.archived": "已归档",
    "common.attendance": "考勤",
    "common.attendance_management": "考勤管理",
    "common.attendance_records": "出勤记录",
    "common.auto_backup": "自动备份",
    "common.average": "一般",
    "common.average_score": "平均分",
    "common.back": "返回",
    "common.back_to_home": "返回首页",
    "common.bank_name": "银行名称",
    "common.bank_reconciliation": "银行对账",
    "common.basic_info": "基本信息",
    "common.biology": "生物",
    "common.birthday": "生日",
    "common.budget_management": "预算管理",
    "common.cancel": "取消",
    "common.card_list": "卡片列表",
    "common.card_management": "卡片管理",
    "common.card_type": "卡片类型",
    "common.category": "分类",
    "common.center": "中心",
    "common.center_management": "分行管理",
    "common.check_in": "签到",
    "common.check_out": "签退",
    "common.chemistry": "化学",
    "common.chinese": "语文",
    "common.class_name": "班级名称",
    "common.collapse": "收起",
    "common.completed": "已完成",
    "common.confirm": "确认",
    "common.confirm_delete": "确认删除",
    "common.confirm_password": "确认密码",
    "common.connection_failed": "连接失败",
    "common.count": "人数",
    "common.course": "课程",
    "common.course_management": "课程管理",
    "common.course_name": "课程名称",
    "common.created_at": "创建时间",
    "common.daily_logs": "每日日志",
    "common.dashboard": "仪表板",
    "common.data_analysis": "数据分析",
    "common.data_backup": "数据备份",
    "common.data_sync": "数据同步",
    "common.date": "日期",
    "common.delete": "删除",
    "common.delete_failed": "删除失败",
    "common.description": "描述",
    "common.details": "详情",
    "common.disabled": "已关闭",
    "common.draft": "草稿",
    "common.edit_card": "编辑卡片",
    "common.edit_class": "编辑班级",
    "common.edit_course": "编辑课程",
    "common.edit_user": "编辑用户",
    "common.education": "教务",
    "common.email": "邮箱",
    "common.email_address": "邮箱地址",
    "common.emergency_contact": "紧急联系人",
    "common.end_date": "结束日期",
    "common.english": "英语",
    "common.enter_password": "请输入密码",
    "common.exam_name": "考试名称",
    "common.expand": "展开",
    "common.expense_management": "支出管理",
    "common.export_data": "导出数据",
    "common.failed": "失败",
    "common.father": "父亲",
    "common.fee_management": "收费管理",
    "common.finance": "财务",
    "common.finance_desk": "财务工作台",
    "common.finance_overview": "财务概览",
    "common.financial_report": "财务报表",
    "common.geography": "地理",
    "common.grade": "年级",
    "common.grade_distribution": "成绩分布",
    "common.grade_management": "成绩管理",
    "common.graded": "已批改",
    "common.grades_query": "成绩查询",
    "common.guardian": "监护人",
    "common.history": "历史",
    "common.homework": "作业",
    "common.homework_list": "作业列表",
    "common.homework_management": "作业管理",
    "common.homework_title": "作业标题",
    "common.in_progress": "进行中",
    "common.inactive": "非活跃",
    "common.insufficient_permissions": "权限不足",
    "common.inventory_management": "库存管理",
    "common.invoice_management": "发票管理",
    "common.loading...": "加载中...",
    "common.login": "登录",
    "common.lost": "丢失",
    "common.mathematics": "数学",
    "common.mother": "母亲",
    "common.music": "音乐",
    "common.my_kids": "孩子总览",
    "common.my_workspace": "我的工作台",
    "common.name": "姓名",
    "common.network_error": "网络错误",
    "common.next": "下一页",
    "common.nfc": "NFC",
    "common.no_data": "无数据",
    "common.no_records": "暂无记录",
    "common.no_users": "暂无用户",
    "common.normal": "正常",
    "common.not_set": "未设置",
    "common.not_submitted": "未提交",
    "common.not_verified": "未验证",
    "common.notes": "备注",
    "common.notification": "通知",
    "common.notification_center": "通知中心",
    "common.notification_type": "通知类型",
    "common.offline": "离线",
    "common.online": "在线",
    "common.operation_failed": "操作失败",
    "common.optional": "可选",
    "common.other": "其他",
    "common.overdue": "逾期",
    "common.overview": "概览",
    "common.parent": "家长",
    "common.parent_portal": "家长门户",
    "common.pass_rate": "及格率",
    "common.password": "密码",
    "common.paused": "已暂停",
    "common.payment_management": "付款管理",
    "common.payment_records": "缴费记录",
    "common.payroll_management": "薪资管理",
    "common.pending": "待处理",
    "common.pending_review": "待审核",
    "common.phone": "手机",
    "common.physical_education": "体育",
    "common.physics": "物理",
    "common.pickup_management": "接送管理",
    "common.points": "积分操作",
    "common.points_leaderboard": "积分排行",
    "common.points_rules": "积分规则",
    "common.previous": "上一页",
    "common.primary": "小学",
    "common.priority": "优先级",
    "common.processing...": "处理中...",
    "common.published": "已发布",
    "common.quantity": "数量",
    "common.quick_filters": "快速筛选",
    "common.read": "已读",
    "common.receipt_management": "收据管理",
    "common.register": "注册",
    "common.registration_time": "注册时间",
    "common.reject": "拒绝",
    "common.rejected": "已拒绝",
    "common.relationship": "关系",
    "common.report_lost": "挂失",
    "common.reset_password": "重置密码",
    "common.resource_library": "资源库",
    "common.reviewed": "已审核",
    "common.role": "角色",
    "common.save": "保存",
    "common.save_failed": "保存失败",
    "common.save_settings": "保存设置",
    "common.saving...": "保存中...",
    "common.scheduled": "已安排",
    "common.science": "科学",
    "common.score": "得分",
    "common.search": "搜索",
    "common.search_cards": "搜索卡片",
    "common.search_users": "搜索用户",
    "common.secondary": "中学",
    "common.select_student": "选择学生",
    "common.select_subject": "选择科目",
    "common.select_teacher": "选择教师",
    "common.selected": "已选择",
    "common.settings": "设置",
    "common.slideshow": "幻灯片",
    "common.sort_by": "排序方式",
    "common.start_date": "开始日期",
    "common.status": "状态",
    "common.status_filter": "状态筛选",
    "common.stock_in": "入库",
    "common.stock_out": "出库",
    "common.student": "学生",
    "common.student_check_in": "学生签到",
    "common.student_fees": "学生费用",
    "common.student_list": "学生列表",
    "common.student_name": "学生姓名",
    "common.student_no.": "学号",
    "common.subject": "科目",
    "common.subject_filter": "科目筛选",
    "common.submit_time": "提交时间",
    "common.submitting...": "提交中...",
    "common.success": "成功",
    "common.supplier": "供应商",
    "common.system": "系统",
    "common.system_normal": "系统正常",
    "common.system_notification": "系统通知",
    "common.system_settings": "系统设置",
    "common.teacher": "教师",
    "common.teacher_attendance": "教师考勤",
    "common.teacher_list": "教师列表",
    "common.this_week": "本周",
    "common.time": "时间",
    "common.title": "标题",
    "common.today": "今天",
    "common.tv_board": "TV看板",
    "common.type": "类型",
    "common.type_filter": "类型筛选",
    "common.under_maintenance": "维护中",
    "common.unit": "单位",
    "common.unit_price": "单价",
    "common.unknown": "未知",
    "common.unknown_error": "未知错误",
    "common.unknown_student": "未知学生",
    "common.unread": "未读",
    "common.updating...": "更新中...",
    "common.user": "用户",
    "common.user_details": "用户详情",
    "common.user_does_not_exist": "用户不存在",
    "common.user_list": "用户列表",
    "common.user_management": "用户管理",
    "common.verified": "已验证",
    "common.year_1": "一年级",
    "common.year_2": "二年级",
    "common.year_3": "三年级",
    "common.year_4": "四年级",
    "common.year_5": "五年级",
    "common.year_6": "六年级",
    "common.yesterday": "昨天",
    "course.absent_count": "缺勤人数",
    "course.actions": "操作",
    "course.active": "活跃",
    "course.all_grades": "全部年级",
    "course.art": "美术",
    "course.attendance_rate": "出勤率",
    "course.chinese": "华文",
    "course.course": "课程",
    "course.course_details": "课程详情",
    "course.course_management": "课程管理",
    "course.course_name": "课程名称",
    "course.course_time": "课程时间",
    "course.edit_course": "编辑课程",
    "course.ended": "已结束",
    "course.english": "英文",
    "course.friday": "周五",
    "course.geography": "地理",
    "course.grade": "年级",
    "course.grade_filter": "年级筛选",
    "course.history": "历史",
    "course.in_progress": "进行中",
    "course.inactive": "非活跃",
    "course.load_failed": "加载失败",
    "course.loading...": "加载中...",
    "course.malay": "国文",
    "course.mathematics": "数学",
    "course.monday": "周一",
    "course.moral": "道德",
    "course.music": "音乐",
    "course.paused": "已暂停",
    "course.physical_education": "体育",
    "course.present_count": "出勤人数",
    "course.retry": "重试",
    "course.science": "科学",
    "course.status": "状态",
    "course.subject": "科目",
    "course.system_normal": "系统正常",
    "course.teacher": "教师",
    "course.thursday": "周四",
    "course.time": "时间",
    "course.total_courses": "总课程数",
    "course.total_students": "总学生数",
    "course.tuesday": "周二",
    "course.view_details": "查看详情",
    "course.wednesday": "周三",
    "course.week": "星期",
    "course.year_1": "一年级",
    "course.year_2": "二年级",
    "course.year_3": "三年级",
    "course.year_4": "四年级",
    "course.year_5": "五年级",
    "course.year_6": "六年级",
    "dailylog.create_failed": "创建失败",
    "dailylog.daily_logs": "每日日志",
    "dailylog.loading...": "加载中...",
    "dailylog.notes": "备注",
    "dailylog.today": "今天",
    "dailylog.unknown_student": "未知学生",
    "dailylog.update_failed": "更新失败",
    "dailylog.yesterday": "昨天",
    "dashboard.active_students": "在读学生",
    "dashboard.add": "添加",
    "dashboard.admin": "管理员",
    "dashboard.all": "全部",
    "dashboard.annual_report": "年度报表",
    "dashboard.attendance_rate": "出勤率",
    "dashboard.cancel": "取消",
    "dashboard.edit": "编辑",
    "dashboard.enrolled": "在读",
    "dashboard.expense": "支出",
    "dashboard.female": "女",
    "dashboard.finance_management": "财务管理",
    "dashboard.financial_report": "财务报表",
    "dashboard.grade": "成绩",
    "dashboard.graduated": "已毕业",
    "dashboard.homework": "作业",
    "dashboard.income": "收入",
    "dashboard.left_school": "离校",
    "dashboard.loading...": "加载中...",
    "dashboard.log": "日志",
    "dashboard.male": "男",
    "dashboard.monthly_report": "月度报表",
    "dashboard.no_data": "暂无数据",
    "dashboard.overview": "概览",
    "dashboard.parent_portal": "家长门户",
    "dashboard.points": "积分",
    "dashboard.points_leaderboard": "积分排行",
    "dashboard.present": "出勤",
    "dashboard.quick_actions": "快速操作",
    "dashboard.refund": "退款",
    "dashboard.save": "保存",
    "dashboard.secondary": "中学",
    "dashboard.this_month's_birthdays": "本月生日",
    "dashboard.today": "今天",
    "dashboard.total_expenses": "总支出",
    "dashboard.total_income": "总收入",
    "dashboard.total_students": "总学生数",
    "dashboard.total_teachers": "总教师数",
    "dashboard.unknown": "未知",
    "dashboard.view": "查看",
    "dashboard.year_3": "三年级",
    "dashboard.yesterday": "昨天",
    "education.april": "四月",
    "education.august": "八月",
    "education.cancelled": "已取消",
    "education.class": "班级",
    "education.completed": "已完成",
    "education.confirmed": "已确认",
    "education.course": "课程",
    "education.december": "十二月",
    "education.february": "二月",
    "education.in_progress": "进行中",
    "education.january": "一月",
    "education.july": "七月",
    "education.june": "六月",
    "education.march": "三月",
    "education.may": "五月",
    "education.november": "十一月",
    "education.october": "十月",
    "education.september": "九月",
    "education.student": "学生",
    "education.teacher": "教师",
    "finance.account_number": "账户号码",
    "finance.actions": "操作",
    "finance.active": "活跃",
    "finance.all": "全部",
    "finance.amount": "金额",
    "finance.back": "返回",
    "finance.bank_account": "银行账户",
    "finance.bank_name": "银行名称",
    "finance.bank_reconciliation": "银行对账",
    "finance.bank_transfer": "银行转账",
    "finance.basic_info": "基本信息",
    "finance.budget_management": "预算管理",
    "finance.cancel": "取消",
    "finance.cancelled": "已取消",
    "finance.cash": "现金",
    "finance.clear_selection": "取消选择",
    "finance.click_to_upload": "点击上传",
    "finance.completed": "已完成",
    "finance.confirm_delete": "确认删除",
    "finance.date": "日期",
    "finance.default_settings": "默认设置",
    "finance.delete_failed": "删除失败",
    "finance.deleted": "已删除",
    "finance.description": "描述",
    "finance.disable": "禁用",
    "finance.disabled": "停用",
    "finance.draft": "草稿",
    "finance.edit": "编辑",
    "finance.email": "邮箱",
    "finance.enable": "启用",
    "finance.expense": "支出",
    "finance.expense_management": "支出管理",
    "finance.failed": "失败",
    "finance.fee_management": "收费管理",
    "finance.finance_overview": "财务概览",
    "finance.financial_report": "财务报表",
    "finance.grade": "年级",
    "finance.import_failed": "导入失败",
    "finance.income": "收入",
    "finance.invoice_management": "发票管理",
    "finance.invoice_no.": "发票编号",
    "finance.loading...": "加载中...",
    "finance.no_expense_records": "暂无支出记录",
    "finance.no_payment_records": "暂无付款记录",
    "finance.none": "无",
    "finance.normal": "正常",
    "finance.notes": "备注",
    "finance.other": "其他",
    "finance.overdue": "逾期",
    "finance.paid": "已付款",
    "finance.payment_management": "付款管理",
    "finance.payroll_management": "薪资管理",
    "finance.pending": "待处理",
    "finance.pending_payment": "待付款",
    "finance.phone": "电话",
    "finance.primary": "小学",
    "finance.processing": "处理中",
    "finance.receipt_list": "收据列表",
    "finance.receipt_management": "收据管理",
    "finance.salary": "薪资",
    "finance.save": "保存",
    "finance.save_failed": "保存失败",
    "finance.scheduled": "已安排",
    "finance.school_info": "学校信息",
    "finance.search": "搜索",
    "finance.secondary": "中学",
    "finance.select_all": "全选",
    "finance.select_student": "选择学生",
    "finance.send_failed": "发送失败",
    "finance.sent": "已发送",
    "finance.status": "状态",
    "finance.student": "学生",
    "finance.student_fees": "学生费用",
    "finance.student_name": "学生姓名",
    "finance.student_no.": "学号",
    "finance.system_normal": "系统正常",
    "finance.total": "总计",
    "finance.total_expenses": "总支出",
    "finance.total_income": "总收入",
    "finance.type": "类型",
    "finance.unknown": "未知",
    "finance.unknown_student": "未知学生",
    "finance.year_1": "一年级",
    "finance.year_2": "二年级",
    "finance.year_3": "三年级",
    "finance.year_4": "四年级",
    "finance.year_5": "五年级",
    "finance.year_6": "六年级",
    "grade.actions": "操作",
    "grade.art": "美术",
    "grade.average_score": "平均分",
    "grade.cancel": "取消",
    "grade.chinese": "华文",
    "grade.english": "英文",
    "grade.geography": "地理",
    "grade.grade": "年级",
    "grade.grade_management": "成绩管理",
    "grade.highest_score": "最高分",
    "grade.history": "历史",
    "grade.lowest_score": "最低分",
    "grade.malay": "国文",
    "grade.mathematics": "数学",
    "grade.moral": "道德",
    "grade.music": "音乐",
    "grade.other": "其他",
    "grade.pass_rate": "及格率",
    "grade.physical_education": "体育",
    "grade.save": "保存",
    "grade.science": "科学",
    "grade.student": "学生",
    "grade.year": "年份",
    "homework.all_centers": "全部中心",
    "homework.all_grades": "全部年级",
    "homework.all_subjects": "全部科目",
    "homework.art": "美术",
    "homework.center": "所属中心",
    "homework.chinese": "华文",
    "homework.english": "英文",
    "homework.geography": "地理",
    "homework.grade": "年级",
    "homework.graded": "已批改",
    "homework.history": "历史",
    "homework.homework_management": "作业管理",
    "homework.load_failed": "加载失败",
    "homework.loading...": "加载中...",
    "homework.mathematics": "数学",
    "homework.moral": "道德",
    "homework.music": "音乐",
    "homework.not_submitted": "未提交",
    "homework.other": "其他",
    "homework.physical_education": "体育",
    "homework.save_failed": "保存失败",
    "homework.saving...": "保存中...",
    "homework.science": "科学",
    "homework.select_subject": "选择科目",
    "homework.select_teacher": "选择教师",
    "homework.subject": "科目",
    "homework.submitted": "已提交",
    "homework.year_1": "一年级",
    "homework.year_2": "二年级",
    "homework.year_3": "三年级",
    "homework.year_4": "四年级",
    "homework.year_5": "五年级",
    "homework.year_6": "六年级",
    "inventory.actions": "操作",
    "inventory.all_status": "全部状态",
    "inventory.cancel": "取消",
    "inventory.category": "分类",
    "inventory.description": "描述",
    "inventory.details": "详情",
    "inventory.inventory_management": "库存管理",
    "inventory.retry": "重试",
    "inventory.save_failed": "保存失败",
    "inventory.saving...": "保存中...",
    "inventory.status": "状态",
    "inventory.unit": "单位",
    "parent.actions": "操作",
    "parent.active": "活跃",
    "parent.add": "添加",
    "parent.address": "地址",
    "parent.average_score": "平均分",
    "parent.cancel": "取消",
    "parent.delete_failed": "删除失败",
    "parent.disabled": "停用",
    "parent.father": "父亲",
    "parent.grades_query": "成绩查询",
    "parent.guardian": "监护人",
    "parent.home_address": "家庭地址",
    "parent.loading...": "加载中...",
    "parent.mother": "母亲",
    "parent.name": "姓名",
    "parent.no_data": "暂无数据",
    "parent.notes": "备注",
    "parent.other": "其他",
    "parent.overdue": "逾期",
    "parent.paid": "已付款",
    "parent.parent_name": "家长姓名",
    "parent.pass_rate": "及格率",
    "parent.payment_records": "缴费记录",
    "parent.pending_payment": "待付款",
    "parent.phone": "电话",
    "parent.relationship": "关系",
    "parent.save_failed": "保存失败",
    "parent.saving...": "保存中...",
    "parent.status": "状态",
    "parent.unknown_student": "未知学生",
    "parent.update": "更新",
    "points.all": "全部",
    "points.disabled": "停用",
    "points.enable": "启用",
    "points.late": "迟到",
    "points.loading...": "加载中...",
    "points.no_records": "暂无记录",
    "points.operation_failed": "操作失败",
    "points.points": "积分操作",
    "points.points_rules": "积分规则",
    "points.student": "学生",
    "points.teacher": "教师",
    "points.time": "时间",
    "points.unknown": "未知",
    "report.art": "美术",
    "report.average_score": "平均分",
    "report.basic_info": "基本信息",
    "report.cancel": "取消",
    "report.chinese": "华文",
    "report.click_to_upload": "点击上传",
    "report.custom": "自定义",
    "report.default_settings": "默认设置",
    "report.email": "邮箱",
    "report.english": "英文",
    "report.excellent": "优秀",
    "report.geography": "地理",
    "report.good": "良好",
    "report.history": "历史",
    "report.june": "六月",
    "report.malay": "国文",
    "report.mathematics": "数学",
    "report.moral": "道德",
    "report.pass": "及格",
    "report.phone": "电话",
    "report.physical_education": "体育",
    "report.save": "保存",
    "report.school_info": "学校信息",
    "report.science": "科学",
    "report.subject": "学科",
    "report.title": "标题",
    "report.year_4": "四年级",
    "resource.system_normal": "系统正常",
    "student.": "了",
    "student.actions": "操作",
    "student.active_students": "在读学生",
    "student.add": "添加",
    "student.add_student": "添加学生",
    "student.advanced_filters": "高级筛选",
    "student.all": "全部",
    "student.all_centers": "全部中心",
    "student.all_grades": "全部年级",
    "student.all_status": "全部状态",
    "student.all_students": "全部学生",
    "student.archived": "已归档",
    "student.art": "美术",
    "student.ascending": "升序",
    "student.basic_info": "基本信息",
    "student.batch_delete": "批量删除",
    "student.cancel": "取消",
    "student.center": "中心",
    "student.chinese": "华文",
    "student.close": "关闭",
    "student.contact_info": "联系方式",
    "student.contact_phone": "联系电话",
    "student.created_at": "创建时间",
    "student.data_load_failed": "数据加载失败",
    "student.date_of_birth": "出生日期",
    "student.days": "天",
    "student.descending": "降序",
    "student.draft": "草稿",
    "student.edit": "编辑",
    "student.edit_student": "编辑学生",
    "student.email": "邮箱",
    "student.email_address": "邮箱地址",
    "student.english": "英文",
    "student.enrolled": "在读",
    "student.father": "父亲",
    "student.female": "女",
    "student.form_1": "中一",
    "student.form_2": "中二",
    "student.form_3": "中三",
    "student.form_4": "中四",
    "student.form_5": "中五",
    "student.from": "从",
    "student.gender": "性别",
    "student.geography": "地理",
    "student.grade": "年级",
    "student.graduated": "已毕业",
    "student.history": "历史",
    "student.home_address": "家庭地址",
    "student.inactive": "非活跃",
    "student.invalid_email_format": "邮箱格式不正确",
    "student.left_school": "离校",
    "student.level": "级别",
    "student.loading...": "加载中...",
    "student.malay": "国文",
    "student.male": "男",
    "student.mathematics": "数学",
    "student.moral": "道德",
    "student.mother": "母亲",
    "student.name": "姓名",
    "student.no": "否",
    "student.no_student_data": "暂无学生数据",
    "student.none": "无",
    "student.not_set": "未设置",
    "student.overdue": "逾期",
    "student.paid": "已付款",
    "student.parent": "家长",
    "student.pending_payment": "待付款",
    "student.phone": "电话",
    "student.physical_education": "体育",
    "student.published": "已发布",
    "student.quick_filters": "快速筛选",
    "student.real_time_data": "实时数据",
    "student.relationship": "关系",
    "student.save_failed": "保存失败",
    "student.saving...": "保存中...",
    "student.school": "就读学校",
    "student.school_info": "学校信息",
    "student.science": "科学",
    "student.select_date": "请选择日期",
    "student.select_file": "选择文件",
    "student.select_grade": "请选择年级",
    "student.semester": "学期",
    "student.sort": "排序",
    "student.status": "状态",
    "student.student": "学生",
    "student.student_details": "学生详情",
    "student.student_list": "学生列表",
    "student.student_management": "学生管理",
    "student.student_name": "学生姓名",
    "student.student_no.": "学号",
    "student.suspended": "已停学",
    "student.system_normal": "系统正常",
    "student.total_students": "总学生数",
    "student.unknown": "未知",
    "student.unknown_error": "未知错误",
    "student.update": "更新",
    "student.update_failed": "更新失败",
    "student.year": "年份",
    "student.year_1": "一年级",
    "student.year_2": "二年级",
    "student.year_3": "三年级",
    "student.year_4": "四年级",
    "student.year_5": "五年级",
    "student.year_6": "六年级",
    "student.yes": "是",
    "teacher.absent": "缺勤",
    "teacher.account_number": "账户号码",
    "teacher.actions": "操作",
    "teacher.active": "在职",
    "teacher.add": "添加",
    "teacher.add_teacher": "添加教师",
    "teacher.address": "地址",
    "teacher.advanced_filters": "高级筛选",
    "teacher.all_centers": "全部中心",
    "teacher.all_grades": "全部年级",
    "teacher.all_status": "全部状态",
    "teacher.all_subjects": "全部科目",
    "teacher.all_teachers": "全部教师",
    "teacher.approved": "已批准",
    "teacher.archived": "已归档",
    "teacher.attendance_management": "考勤管理",
    "teacher.attendance_rate": "出勤率",
    "teacher.average": "一般",
    "teacher.bank_name": "银行名称",
    "teacher.basic_info": "基本信息",
    "teacher.batch_delete": "批量删除",
    "teacher.biology": "生物",
    "teacher.cancel": "取消",
    "teacher.cancelled": "已取消",
    "teacher.center": "中心",
    "teacher.check_in_time": "签到时间",
    "teacher.check_out_time": "签退时间",
    "teacher.checked_in": "已签到",
    "teacher.chemistry": "化学",
    "teacher.chinese": "语文",
    "teacher.close": "关闭",
    "teacher.collapse": "收起",
    "teacher.completed": "已完成",
    "teacher.confirmed": "已确认",
    "teacher.contact_info": "联系方式",
    "teacher.contact_phone": "联系电话",
    "teacher.content": "内容",
    "teacher.create_failed": "创建失败",
    "teacher.created_at": "创建时间",
    "teacher.custom": "自定义",
    "teacher.dashboard": "仪表板",
    "teacher.data_format_error": "数据格式错误",
    "teacher.date": "日期",
    "teacher.date_of_birth": "出生日期",
    "teacher.default_settings": "默认设置",
    "teacher.delete_failed": "删除失败",
    "teacher.deleted_successfully": "删除成功",
    "teacher.draft": "草稿",
    "teacher.early_leave": "早退",
    "teacher.edit_course": "编辑课程",
    "teacher.edit_teacher": "编辑教师",
    "teacher.eis": "就业保险",
    "teacher.email": "邮箱",
    "teacher.emergency_contact": "紧急联系人",
    "teacher.end_date": "结束日期",
    "teacher.english": "英语",
    "teacher.enrolled": "在读",
    "teacher.enrollment_date": "入学日期",
    "teacher.enter_address": "请输入地址",
    "teacher.enter_email": "请输入邮箱",
    "teacher.excellent": "优秀",
    "teacher.expand": "展开",
    "teacher.friday": "周五",
    "teacher.generating...": "生成中...",
    "teacher.geography": "地理",
    "teacher.good": "良好",
    "teacher.grade": "年级",
    "teacher.graduated": "已毕业",
    "teacher.guardian": "监护人",
    "teacher.history": "历史",
    "teacher.homework": "作业",
    "teacher.homework_management": "作业管理",
    "teacher.in_progress": "进行中",
    "teacher.inactive": "非活跃",
    "teacher.late": "迟到",
    "teacher.leave": "请假",
    "teacher.loading...": "加载中...",
    "teacher.lost": "丢失",
    "teacher.mathematics": "数学",
    "teacher.monday": "周一",
    "teacher.music": "音乐",
    "teacher.name": "姓名",
    "teacher.network_error": "网络错误",
    "teacher.no": "否",
    "teacher.none": "无",
    "teacher.normal": "正常",
    "teacher.not_set": "未设置",
    "teacher.notes": "备注",
    "teacher.notification_center": "通知中心",
    "teacher.notification_details": "通知详情",
    "teacher.now": "现在",
    "teacher.operation_failed": "操作失败",
    "teacher.paid": "已支付",
    "teacher.paused": "已暂停",
    "teacher.payroll_management": "薪资管理",
    "teacher.pending_review": "待审核",
    "teacher.phone": "电话",
    "teacher.physical_education": "体育",
    "teacher.physics": "物理",
    "teacher.points": "积分操作",
    "teacher.points_leaderboard": "积分排行",
    "teacher.present": "出勤",
    "teacher.priority": "优先级",
    "teacher.quick_actions": "快速操作",
    "teacher.quick_filters": "快速筛选",
    "teacher.read": "已读",
    "teacher.reject": "拒绝",
    "teacher.rejected": "已拒绝",
    "teacher.reload": "重新加载",
    "teacher.resignation_date": "离职日期",
    "teacher.resigned": "离职",
    "teacher.reviewed": "已审核",
    "teacher.saturday": "周六",
    "teacher.science": "科学",
    "teacher.search": "搜索",
    "teacher.search_students": "搜索学生",
    "teacher.select_all": "全选",
    "teacher.select_date": "请选择日期",
    "teacher.select_file": "选择文件",
    "teacher.select_student": "选择学生",
    "teacher.select_subject": "选择科目",
    "teacher.select_teacher": "选择教师",
    "teacher.settings": "设置",
    "teacher.sort_by": "排序方式",
    "teacher.start_date": "开始日期",
    "teacher.status": "状态",
    "teacher.student_check_in": "学生签到",
    "teacher.student_list": "学生列表",
    "teacher.student_management": "学生管理",
    "teacher.subject": "科目",
    "teacher.submitted": "已提交",
    "teacher.submitting...": "提交中...",
    "teacher.sunday": "周日",
    "teacher.system": "系统",
    "teacher.system_normal": "系统正常",
    "teacher.system_notification": "系统通知",
    "teacher.teacher": "教师",
    "teacher.teacher_list": "教师列表",
    "teacher.teacher_name": "教师姓名",
    "teacher.thursday": "周四",
    "teacher.time_range": "时间范围",
    "teacher.timetable": "课程表",
    "teacher.title": "标题",
    "teacher.today": "今天",
    "teacher.today's_classes": "今日课程",
    "teacher.total_courses": "总课程数",
    "teacher.total_students": "总学生数",
    "teacher.total_teachers": "总教师数",
    "teacher.tuesday": "周二",
    "teacher.type": "类型",
    "teacher.unknown": "未知",
    "teacher.unknown_error": "未知错误",
    "teacher.unknown_student": "未知学生",
    "teacher.unread": "未读",
    "teacher.unread_notifications": "未读通知",
    "teacher.update": "更新",
    "teacher.updated_at": "更新时间",
    "teacher.verified": "已验证",
    "teacher.vs_last_month": "较上月",
    "teacher.wednesday": "周三",
    "teacher.year": "年份",
    "teacher.year_3": "三年级",
    "teacher.yes": "是",
    "tv.loading...": "加载中...",
    "tv.no_data": "暂无数据",
    "user.actions": "操作",
    "user.admin": "管理员",
    "user.back_to_home": "返回首页",
    "user.delete": "删除",
    "user.email": "邮箱",
    "user.name": "姓名",
    "user.no_users": "暂无用户",
    "user.registration_time": "注册时间",
    "user.role": "角色",
    "user.verify": "验证",



    "admin.analyzing": "分析中...",
    "admin.registration_time": "注册时间",
    "admin.this_week": "本周",
    "admin.user_details": "用户详情",
    "admin.yesterday": "昨天",
    "announcement.notification_center": "通知中心",
    "announcement.notification_type": "通知类型",
    "announcement.priority": "优先级",
    "announcement.system_notification": "系统通知",
    "announcement.time": "时间",
    "assignment.biology": "生物",
    "assignment.chemistry": "化学",
    "assignment.chinese": "语文",
    "assignment.completed": "已完成",
    "assignment.english": "英语",
    "assignment.geography": "地理",
    "assignment.graded": "已批改",
    "assignment.history": "历史",
    "assignment.homework_list": "作业列表",
    "assignment.homework_title": "作业标题",
    "assignment.in_progress": "进行中",
    "assignment.mathematics": "数学",
    "assignment.physics": "物理",
    "assignment.science": "科学",
    "assignment.select_subject": "选择科目",
    "assignment.submit_time": "提交时间",
    "attendance.data_sync": "数据同步",
    "attendance.phone": "手机",
    "attendance.todays_attendance": "今日考勤",
    "card.all": "全部",
    "card.card_list": "卡片列表",
    "card.delete": "删除",
    "card.next": "下一页",
    "card.previous": "上一页",
    "card.report_lost": "挂失",
    "center.disabled": "已关闭",
    "common.center_filter": "分行筛选",
    "communication.notification": "通知",
    "course.advanced_filters": "高级筛选",
    "course.all_courses": "全部课程",
    "course.all_subjects": "全部科目",
    "course.archived": "已归档",
    "course.class_name": "班级名称",
    "course.confirm_delete": "确认删除",
    "course.count": "人数",
    "course.created_at": "创建时间",
    "course.quick_filters": "快速筛选",
    "course.scheduled": "已排课",
    "course.sort_by": "排序方式",
    "course.subject_filter": "科目筛选",
    "exam.data_analysis": "数据分析",
    "exam.exam_name": "考试名称",
    "exam.grade_distribution": "成绩分布",
    "exam.grade_management": "成绩管理",
    "exam.pass_rate": "及格率",
    "exam.scheduled": "已安排",
    "exam.score": "得分",
    "exam.subject": "科目",
    "finance.invoice_no": "发票编号",
    "finance.payment_records": "缴费记录",
    "inventory.back": "返回",
    "inventory.optional": "可选",
    "inventory.quantity": "数量",
    "inventory.supplier": "供应商",
    "inventory.unit_price": "单价",
    "pickup.confirm": "确认",
    "pickup.pickup_management": "接送管理",
    "student.student_no": "学号",
    "system.auto_backup": "自动备份",
    "system.back_to_home": "返回首页",
    "system.details": "详情",
    "system.system_settings": "系统设置",
    "system.user": "用户",
    "teacher.generating": "生成中...",
    "teacher.loading": "加载中...",
    "teacher.todays_classes": "今日课程",
    "user.edit_user": "编辑用户",
    "user.inactive": "非活跃",
    "user.search_users": "搜索用户",
    "user.user_list": "用户列表",
    "user.user_management": "用户管理",

    "admin.analyzing": "分析中...",
    "admin.registration_time": "注册时间",
    "admin.this_week": "本周",
    "admin.user_details": "用户详情",
    "admin.yesterday": "昨天",
    "announcement.notification_center": "通知中心",
    "announcement.notification_type": "通知类型",
    "announcement.priority": "优先级",
    "announcement.system_notification": "系统通知",
    "announcement.time": "时间",
    "assignment.biology": "生物",
    "assignment.chemistry": "化学",
    "assignment.chinese": "语文",
    "assignment.completed": "已完成",
    "assignment.english": "英语",
    "assignment.geography": "地理",
    "assignment.graded": "已批改",
    "assignment.history": "历史",
    "assignment.homework_list": "作业列表",
    "assignment.homework_title": "作业标题",
    "assignment.in_progress": "进行中",
    "assignment.mathematics": "数学",
    "assignment.physics": "物理",
    "assignment.science": "科学",
    "assignment.select_subject": "选择科目",
    "assignment.submit_time": "提交时间",
    "attendance.data_sync": "数据同步",
    "attendance.phone": "手机",
    "attendance.todays_attendance": "今日考勤",
    "card.all": "全部",
    "card.card_list": "卡片列表",
    "card.delete": "删除",
    "card.next": "下一页",
    "card.previous": "上一页",
    "card.report_lost": "挂失",
    "center.disabled": "已关闭",
    "common.center_filter": "分行筛选",
    "communication.notification": "通知",
    "course.advanced_filters": "高级筛选",
    "course.all_courses": "全部课程",
    "course.all_subjects": "全部科目",
    "course.archived": "已归档",
    "course.class_name": "班级名称",
    "course.confirm_delete": "确认删除",
    "course.count": "人数",
    "course.created_at": "创建时间",
    "course.quick_filters": "快速筛选",
    "course.scheduled": "已排课",
    "course.sort_by": "排序方式",
    "course.subject_filter": "科目筛选",
    "exam.data_analysis": "数据分析",
    "exam.exam_name": "考试名称",
    "exam.grade_distribution": "成绩分布",
    "exam.grade_management": "成绩管理",
    "exam.pass_rate": "及格率",
    "exam.scheduled": "已安排",
    "exam.score": "得分",
    "exam.subject": "科目",
    "finance.invoice_no": "发票编号",
    "finance.payment_records": "缴费记录",
    "inventory.back": "返回",
    "inventory.optional": "可选",
    "inventory.quantity": "数量",
    "inventory.supplier": "供应商",
    "inventory.unit_price": "单价",
    "pickup.confirm": "确认",
    "pickup.pickup_management": "接送管理",
    "student.student_no": "学号",
    "system.auto_backup": "自动备份",
    "system.back_to_home": "返回首页",
    "system.details": "详情",
    "system.system_settings": "系统设置",
    "system.user": "用户",
    "teacher.generating": "生成中...",
    "teacher.loading": "加载中...",
    "teacher.todays_classes": "今日课程",
    "user.edit_user": "编辑用户",
    "user.inactive": "非活跃",
    "user.search_users": "搜索用户",
    "user.user_list": "用户列表",
    "user.user_management": "用户管理",
},
  en: {
    // AppShell
    "app.title": "PJPC After-school Care",
    "app.subtitle": "Professional after-school education management solution",
    "nav.dashboard": "Overview",
    "nav.slideshow": "Slideshow",
    "nav.tv_board": "TV Board",
    "nav.education": "Education",
    "nav.students": "Students",
    "nav.student_reports": "Reports",
    "nav.parents": "Parents",
    "nav.homework": "Homework",
    "nav.grades": "Grades",
    "nav.pickup": "Pickup",
    "nav.daily_logs": "Daily Logs",
    "nav.resource_library": "Resources",
    "nav.teachers": "Teachers",
    "nav.teacher_attendance": "Teacher Attendance",
    "nav.courses": "Courses",
    "nav.finance": "Finance",
    "nav.finance_overview": "Finance Overview",
    "nav.fees": "Fee Management",
    "nav.student_fees": "Student Fees",
    "nav.invoices": "Invoices",
    "nav.payments": "Payments",
    "nav.receipts": "Receipts",
    "nav.payroll": "Payroll",
    "nav.expenses": "Expenses",
    "nav.bank_reconciliation": "Bank Reconciliation",
    "nav.budget": "Budget",
    "nav.financial_reports": "Financial Reports",
    "nav.inventory": "Inventory",
    "nav.system": "System",
    "nav.attendance": "Attendance",
    "nav.card_management": "Cards",
    "nav.points": "Points",
    "nav.points_rules": "Points Rules",
    "nav.points_leaderboard": "Leaderboard",
    "nav.user_management": "Users",
    "nav.center_management": "Centers",
    "nav.settings": "Settings",
    "nav.admin_panel": "Admin Panel",
    "nav.teacher_workspace": "My Workspace",
    "nav.student_checkin": "Student Check-in",
    "nav.parent_portal": "Parent Portal",
    "nav.parent_dashboard": "My Kids",
    "nav.parent_daily_logs": "Daily Logs",
    "nav.parent_grades": "Grades",
    "nav.parent_payments": "Payments",
    "nav.parent_attendance": "Attendance",
    "nav.parent_notifications": "Notifications",
    "nav.accountant_workspace": "Finance Desk",
    "nav.center_filter": "Center",
    "nav.all_centers": "All",
    "nav.edit_nav": "Edit Menu",
    "nav.finish_sort": "Done",
    "nav.reset_default": "Reset",
    "nav.online": "Online",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.notifications": "Notifications",
    "role.admin": "Administrator",
    "role.teacher": "Teacher",
    "role.parent": "Parent",
    "role.accountant": "Accountant",
    // Login page
    "login.title": "PJPC After-school Care",
    "login.subtitle": "Please login to your account",
    "login.card_title": "User Login",
    "login.features": "System Features",
    "login.feature_students": "Student Management",
    "login.feature_attendance": "Attendance Check-in",
    "login.feature_courses": "Course Scheduling",
    "login.feature_points": "Points Rewards",
    // Breadcrumbs
    "breadcrumb.dashboard": "Dashboard",
    "breadcrumb.slideshow": "Slideshow",
    "breadcrumb.education_overview": "Education Overview",
    "breadcrumb.student_list": "Students",
    "breadcrumb.student_reports": "Reports",
    "breadcrumb.daily_logs": "Daily Logs",
    "breadcrumb.grades": "Grades",
    "breadcrumb.pickup": "Pickup",
    "breadcrumb.parents": "Parents",
    "breadcrumb.homework": "Homework",
    "breadcrumb.teachers": "Teachers",
    "breadcrumb.teacher_attendance": "Teacher Attendance",
    "breadcrumb.courses": "Courses",
    "breadcrumb.finance_overview": "Finance Overview",
    "breadcrumb.fees": "Fee Management",
    "breadcrumb.student_fees": "Student Fees",
    "breadcrumb.invoices": "Invoices",
    "breadcrumb.payments": "Payments",
    "breadcrumb.receipts": "Receipts",
    "breadcrumb.payroll": "Payroll",
    "breadcrumb.expenses": "Expenses",
    "breadcrumb.bank": "Bank Reconciliation",
    "breadcrumb.budget": "Budget",
    "breadcrumb.financial_reports": "Financial Reports",
    "breadcrumb.inventory": "Inventory",
    "breadcrumb.attendance": "Attendance",
    "breadcrumb.card_management": "Cards",
    "breadcrumb.points": "Points",
    "breadcrumb.points_rules": "Points Rules",
    "breadcrumb.points_leaderboard": "Leaderboard",
    "breadcrumb.user_management": "Users",
    "breadcrumb.center_management": "Centers",
    "breadcrumb.settings": "Settings",
    "breadcrumb.report_detail": "Report Detail",
    "breadcrumb.loading": "Loading...",
    "breadcrumb.unknown": "Unknown",
  
    "admin.accountant": "Accountant",
    "admin.add": "Add",
    "admin.add_role": "Add Role",
    "admin.admin": "Admin",
    "admin.approved": "Approved",
    "admin.bank_reconciliation": "Bank Reconciliation",
    "admin.budget_management": "Budget Management",
    "admin.card_management": "Card Management",
    "admin.course_management": "Course Management",
    "admin.create_failed": "Create Failed",
    "admin.daily_logs": "Daily Logs",
    "admin.dashboard": "Dashboard",
    "admin.description": "Description",
    "admin.expense_management": "Expense Management",
    "admin.fee_management": "Fee Management",
    "admin.finance_management": "Finance Management",
    "admin.finance_overview": "Finance Overview",
    "admin.financial_report": "Financial Report",
    "admin.grade_management": "Grade Management",
    "admin.insufficient_permissions": "Insufficient Permissions",
    "admin.inventory_management": "Inventory Management",
    "admin.loading...": "Loading...",
    "admin.network_error": "Network Error",
    "admin.no_users": "No users",
    "admin.parent": "Parent",
    "admin.payroll_management": "Payroll Management",
    "admin.pending_review": "Pending Review",
    "admin.pickup_management": "Pickup Management",
    "admin.points": "Points",
    "admin.points_records": "Points Records",
    "admin.rejected": "Rejected",
    "admin.reviewed": "Reviewed",
    "admin.role": "Role",
    "admin.student_list": "Student List",
    "admin.student_management": "Student Management",
    "admin.system_settings": "System Settings",
    "admin.teacher": "Teacher",
    "admin.teacher_list": "Teacher List",
    "admin.teacher_management": "Teacher Management",
    "admin.timetable": "Timetable",
    "admin.update": "Update",
    "admin.user_management": "User Management",
    "attendance.absent": "Absent",
    "attendance.actions": "Actions",
    "attendance.add": "Add",
    "attendance.add_course": "Add Course",
    "attendance.all": "All",
    "attendance.all_centers": "All Centers",
    "attendance.all_status": "All Status",
    "attendance.all_types": "All Types",
    "attendance.approved": "Approved",
    "attendance.attendance_management": "Attendance Management",
    "attendance.attendance_rate": "Attendance Rate",
    "attendance.attendance_records": "Attendance Records",
    "attendance.branch": "Branch",
    "attendance.cancelled": "Cancelled",
    "attendance.center": "Center",
    "attendance.check_in": "Check In",
    "attendance.check_in_time": "Check-in Time",
    "attendance.check_out": "Check Out",
    "attendance.check_out_time": "Check-out Time",
    "attendance.checked_in": "Checked In",
    "attendance.checked_in_count": "Checked In Count",
    "attendance.checked_out": "Checked Out",
    "attendance.chinese": "Chinese",
    "attendance.completed": "Completed",
    "attendance.confirmed": "Confirmed",
    "attendance.course_name": "Course Name",
    "attendance.course_scheduling": "Course Scheduling",
    "attendance.date": "Date",
    "attendance.days": "days",
    "attendance.description": "Description",
    "attendance.disable": "Disable",
    "attendance.early_leave": "Early Leave",
    "attendance.enable": "Enable",
    "attendance.end_time": "End Time",
    "attendance.english": "English",
    "attendance.failed": "Failed",
    "attendance.form_1": "Form 1",
    "attendance.form_2": "Form 2",
    "attendance.form_3": "Form 3",
    "attendance.friday": "Friday",
    "attendance.grade": "Grade",
    "attendance.hours": "hours",
    "attendance.in_progress": "In Progress",
    "attendance.late": "Late",
    "attendance.load_failed": "Load Failed",
    "attendance.loading...": "Loading...",
    "attendance.mathematics": "Mathematics",
    "attendance.monday": "Monday",
    "attendance.name": "Name",
    "attendance.nfc": "NFC",
    "attendance.no_data": "No Data",
    "attendance.notes": "Notes",
    "attendance.offline": "Offline",
    "attendance.online": "Online",
    "attendance.operation_failed": "Operation Failed",
    "attendance.present": "Present",
    "attendance.rejected": "Rejected",
    "attendance.saturday": "Saturday",
    "attendance.save_failed": "Save Failed",
    "attendance.scheduled": "Scheduled",
    "attendance.science": "Science",
    "attendance.search_students": "Search Students",
    "attendance.select_subject": "Select Subject",
    "attendance.select_teacher": "Select Teacher",
    "attendance.start_time": "Start Time",
    "attendance.status": "Status",
    "attendance.student": "Student",
    "attendance.student_name": "Student Name",
    "attendance.subject": "Subject",
    "attendance.success": "Success",
    "attendance.sunday": "Sunday",
    "attendance.teacher": "Teacher",
    "attendance.thursday": "Thursday",
    "attendance.time": "Time",
    "attendance.time_range": "Time Range",
    "attendance.today": "Today",
    "attendance.today's_attendance": "Today's Attendance",
    "attendance.total_people": "Total People",
    "attendance.tuesday": "Tuesday",
    "attendance.type": "Type",
    "attendance.under_maintenance": "Under Maintenance",
    "attendance.unknown": "Unknown",
    "attendance.wednesday": "Wednesday",
    "attendance.weekend": "Weekend",
    "attendance.workday": "Workday",
    "attendance.year": "Year",
    "attendance.year_1": "Year 1",
    "attendance.year_2": "Year 2",
    "attendance.year_3": "Year 3",
    "attendance.year_4": "Year 4",
    "attendance.year_5": "Year 5",
    "attendance.year_6": "Year 6",
    "auth.accountant": "Accountant",
    "auth.admin": "Admin",
    "auth.after_school_care_management_system": "After-school Care Management System",
    "auth.confirm_password": "Confirm Password",
    "auth.email_address": "Email Address",
    "auth.enter_password": "Enter Password",
    "auth.login": "Login",
    "auth.name": "Name",
    "auth.parent": "Parent",
    "auth.password": "Password",
    "auth.register": "Register",
    "auth.reset_password": "Reset Password",
    "card.actions": "Actions",
    "card.active": "Active",
    "card.add": "Add",
    "card.balance": "Balance",
    "card.card_status": "Card Status",
    "card.card_type": "Card Type",
    "card.check_in": "Check In",
    "card.check_out": "Check Out",
    "card.data_sync": "Data Sync",
    "card.disabled": "Disabled",
    "card.edit_card": "Edit Card",
    "card.lost": "Lost",
    "card.nfc": "NFC",
    "card.normal": "Normal",
    "card.not_set": "Not Set",
    "card.notes": "Notes",
    "card.processing...": "Processing...",
    "card.status": "Status",
    "card.student": "Student",
    "card.student_name": "Student Name",
    "card.teacher": "Teacher",
    "card.update": "Update",
    "common.account_number": "Account Number",
    "common.accountant": "Accountant",
    "common.actions": "Actions",
    "common.active": "Active",
    "common.add_card": "Add Card",
    "common.address": "Address",
    "common.admin": "Admin",
    "common.admin_panel": "Admin Panel",
    "common.advanced_filters": "Advanced Filters",
    "common.all": "All",
    "common.all_courses": "All Courses",
    "common.all_parents": "All Parents",
    "common.all_status": "All Status",
    "common.all_subjects": "All Subjects",
    "common.all_teachers": "All Teachers",
    "common.all_types": "All Types",
    "common.amount": "Amount",
    "common.analyzing...": "Analyzing...",
    "common.approved": "Approved",
    "common.archived": "Archived",
    "common.attendance": "Attendance",
    "common.attendance_management": "Attendance Management",
    "common.attendance_records": "Attendance Records",
    "common.auto_backup": "Auto Backup",
    "common.average": "Average",
    "common.average_score": "Average Score",
    "common.back": "Back",
    "common.back_to_home": "Back to Home",
    "common.bank_name": "Bank Name",
    "common.bank_reconciliation": "Bank Reconciliation",
    "common.basic_info": "Basic Info",
    "common.biology": "Biology",
    "common.birthday": "Birthday",
    "common.budget_management": "Budget Management",
    "common.cancel": "Cancel",
    "common.card_list": "Card List",
    "common.card_management": "Card Management",
    "common.card_type": "Card Type",
    "common.category": "Category",
    "common.center": "Center",
    "common.center_management": "Center Management",
    "common.check_in": "Check In",
    "common.check_out": "Check Out",
    "common.chemistry": "Chemistry",
    "common.chinese": "Chinese",
    "common.class_name": "Class Name",
    "common.collapse": "Collapse",
    "common.completed": "Completed",
    "common.confirm": "Confirm",
    "common.confirm_delete": "Confirm Delete",
    "common.confirm_password": "Confirm Password",
    "common.connection_failed": "Connection Failed",
    "common.count": "Count",
    "common.course": "Course",
    "common.course_management": "Course Management",
    "common.course_name": "Course Name",
    "common.created_at": "Created At",
    "common.daily_logs": "Daily Logs",
    "common.dashboard": "Dashboard",
    "common.data_analysis": "Data Analysis",
    "common.data_backup": "Data Backup",
    "common.data_sync": "Data Sync",
    "common.date": "Date",
    "common.delete": "Delete",
    "common.delete_failed": "Delete Failed",
    "common.description": "Description",
    "common.details": "Details",
    "common.disabled": "Disabled",
    "common.draft": "Draft",
    "common.edit_card": "Edit Card",
    "common.edit_class": "Edit Class",
    "common.edit_course": "Edit Course",
    "common.edit_user": "Edit User",
    "common.education": "Education",
    "common.email": "Email",
    "common.email_address": "Email Address",
    "common.emergency_contact": "Emergency Contact",
    "common.end_date": "End Date",
    "common.english": "English",
    "common.enter_password": "Enter Password",
    "common.exam_name": "Exam Name",
    "common.expand": "Expand",
    "common.expense_management": "Expense Management",
    "common.export_data": "Export Data",
    "common.failed": "Failed",
    "common.father": "Father",
    "common.fee_management": "Fee Management",
    "common.finance": "Finance",
    "common.finance_desk": "Finance Desk",
    "common.finance_overview": "Finance Overview",
    "common.financial_report": "Financial Report",
    "common.geography": "Geography",
    "common.grade": "Grade",
    "common.grade_distribution": "Grade Distribution",
    "common.grade_management": "Grade Management",
    "common.graded": "Graded",
    "common.grades_query": "Grades Query",
    "common.guardian": "Guardian",
    "common.history": "History",
    "common.homework": "Homework",
    "common.homework_list": "Homework List",
    "common.homework_management": "Homework Management",
    "common.homework_title": "Homework Title",
    "common.in_progress": "In Progress",
    "common.inactive": "Inactive",
    "common.insufficient_permissions": "Insufficient Permissions",
    "common.inventory_management": "Inventory Management",
    "common.invoice_management": "Invoice Management",
    "common.loading...": "Loading...",
    "common.login": "Login",
    "common.lost": "Lost",
    "common.mathematics": "Mathematics",
    "common.mother": "Mother",
    "common.music": "Music",
    "common.my_kids": "My Kids",
    "common.my_workspace": "My Workspace",
    "common.name": "Name",
    "common.network_error": "Network Error",
    "common.next": "Next",
    "common.nfc": "NFC",
    "common.no_data": "No Data",
    "common.no_records": "No records",
    "common.no_users": "No users",
    "common.normal": "Normal",
    "common.not_set": "Not Set",
    "common.not_submitted": "Not Submitted",
    "common.not_verified": "Not Verified",
    "common.notes": "Notes",
    "common.notification": "Notification",
    "common.notification_center": "Notification Center",
    "common.notification_type": "Notification Type",
    "common.offline": "Offline",
    "common.online": "Online",
    "common.operation_failed": "Operation Failed",
    "common.optional": "Optional",
    "common.other": "Other",
    "common.overdue": "Overdue",
    "common.overview": "Overview",
    "common.parent": "Parent",
    "common.parent_portal": "Parent Portal",
    "common.pass_rate": "Pass Rate",
    "common.password": "Password",
    "common.paused": "Paused",
    "common.payment_management": "Payment Management",
    "common.payment_records": "Payment Records",
    "common.payroll_management": "Payroll Management",
    "common.pending": "Pending",
    "common.pending_review": "Pending Review",
    "common.phone": "Phone",
    "common.physical_education": "Physical Education",
    "common.physics": "Physics",
    "common.pickup_management": "Pickup Management",
    "common.points": "Points",
    "common.points_leaderboard": "Points Leaderboard",
    "common.points_rules": "Points Rules",
    "common.previous": "Previous",
    "common.primary": "Primary",
    "common.priority": "Priority",
    "common.processing...": "Processing...",
    "common.published": "Published",
    "common.quantity": "Quantity",
    "common.quick_filters": "Quick Filters",
    "common.read": "Read",
    "common.receipt_management": "Receipt Management",
    "common.register": "Register",
    "common.registration_time": "Registration Time",
    "common.reject": "Reject",
    "common.rejected": "Rejected",
    "common.relationship": "Relationship",
    "common.report_lost": "Report Lost",
    "common.reset_password": "Reset Password",
    "common.resource_library": "Resource Library",
    "common.reviewed": "Reviewed",
    "common.role": "Role",
    "common.save": "Save",
    "common.save_failed": "Save Failed",
    "common.save_settings": "Save Settings",
    "common.saving...": "Saving...",
    "common.scheduled": "Scheduled",
    "common.science": "Science",
    "common.score": "Score",
    "common.search": "Search",
    "common.search_cards": "Search Cards",
    "common.search_users": "Search Users",
    "common.secondary": "Secondary",
    "common.select_student": "Select Student",
    "common.select_subject": "Select Subject",
    "common.select_teacher": "Select Teacher",
    "common.selected": "Selected",
    "common.settings": "Settings",
    "common.slideshow": "Slideshow",
    "common.sort_by": "Sort By",
    "common.start_date": "Start Date",
    "common.status": "Status",
    "common.status_filter": "Status Filter",
    "common.stock_in": "Stock In",
    "common.stock_out": "Stock Out",
    "common.student": "Student",
    "common.student_check_in": "Student Check-in",
    "common.student_fees": "Student Fees",
    "common.student_list": "Student List",
    "common.student_name": "Student Name",
    "common.student_no.": "Student No.",
    "common.subject": "Subject",
    "common.subject_filter": "Subject Filter",
    "common.submit_time": "Submit Time",
    "common.submitting...": "Submitting...",
    "common.success": "Success",
    "common.supplier": "Supplier",
    "common.system": "System",
    "common.system_normal": "System Normal",
    "common.system_notification": "System Notification",
    "common.system_settings": "System Settings",
    "common.teacher": "Teacher",
    "common.teacher_attendance": "Teacher Attendance",
    "common.teacher_list": "Teacher List",
    "common.this_week": "This Week",
    "common.time": "Time",
    "common.title": "Title",
    "common.today": "Today",
    "common.tv_board": "TV Board",
    "common.type": "Type",
    "common.type_filter": "Type Filter",
    "common.under_maintenance": "Under Maintenance",
    "common.unit": "Unit",
    "common.unit_price": "Unit Price",
    "common.unknown": "Unknown",
    "common.unknown_error": "Unknown Error",
    "common.unknown_student": "Unknown Student",
    "common.unread": "Unread",
    "common.updating...": "Updating...",
    "common.user": "User",
    "common.user_details": "User Details",
    "common.user_does_not_exist": "User does not exist",
    "common.user_list": "User List",
    "common.user_management": "User Management",
    "common.verified": "Verified",
    "common.year_1": "Year 1",
    "common.year_2": "Year 2",
    "common.year_3": "Year 3",
    "common.year_4": "Year 4",
    "common.year_5": "Year 5",
    "common.year_6": "Year 6",
    "common.yesterday": "Yesterday",
    "course.absent_count": "Absent Count",
    "course.actions": "Actions",
    "course.active": "Active",
    "course.all_grades": "All Grades",
    "course.art": "Art",
    "course.attendance_rate": "Attendance Rate",
    "course.chinese": "Chinese",
    "course.course": "Course",
    "course.course_details": "Course Details",
    "course.course_management": "Course Management",
    "course.course_name": "Course Name",
    "course.course_time": "Course Time",
    "course.edit_course": "Edit Course",
    "course.ended": "Ended",
    "course.english": "English",
    "course.friday": "Friday",
    "course.geography": "Geography",
    "course.grade": "Grade",
    "course.grade_filter": "Grade Filter",
    "course.history": "History",
    "course.in_progress": "In Progress",
    "course.inactive": "Inactive",
    "course.load_failed": "Load Failed",
    "course.loading...": "Loading...",
    "course.malay": "Malay",
    "course.mathematics": "Mathematics",
    "course.monday": "Monday",
    "course.moral": "Moral",
    "course.music": "Music",
    "course.paused": "Paused",
    "course.physical_education": "Physical Education",
    "course.present_count": "Present Count",
    "course.retry": "Retry",
    "course.science": "Science",
    "course.status": "Status",
    "course.subject": "Subject",
    "course.system_normal": "System Normal",
    "course.teacher": "Teacher",
    "course.thursday": "Thursday",
    "course.time": "Time",
    "course.total_courses": "Total Courses",
    "course.total_students": "Total Students",
    "course.tuesday": "Tuesday",
    "course.view_details": "View Details",
    "course.wednesday": "Wednesday",
    "course.week": "Week",
    "course.year_1": "Year 1",
    "course.year_2": "Year 2",
    "course.year_3": "Year 3",
    "course.year_4": "Year 4",
    "course.year_5": "Year 5",
    "course.year_6": "Year 6",
    "dailylog.create_failed": "Create Failed",
    "dailylog.daily_logs": "Daily Logs",
    "dailylog.loading...": "Loading...",
    "dailylog.notes": "Notes",
    "dailylog.today": "Today",
    "dailylog.unknown_student": "Unknown Student",
    "dailylog.update_failed": "Update Failed",
    "dailylog.yesterday": "Yesterday",
    "dashboard.active_students": "Active Students",
    "dashboard.add": "Add",
    "dashboard.admin": "Admin",
    "dashboard.all": "All",
    "dashboard.annual_report": "Annual Report",
    "dashboard.attendance_rate": "Attendance Rate",
    "dashboard.cancel": "Cancel",
    "dashboard.edit": "Edit",
    "dashboard.enrolled": "Enrolled",
    "dashboard.expense": "Expense",
    "dashboard.female": "Female",
    "dashboard.finance_management": "Finance Management",
    "dashboard.financial_report": "Financial Report",
    "dashboard.grade": "Grade",
    "dashboard.graduated": "Graduated",
    "dashboard.homework": "Homework",
    "dashboard.income": "Income",
    "dashboard.left_school": "Left School",
    "dashboard.loading...": "Loading...",
    "dashboard.log": "Log",
    "dashboard.male": "Male",
    "dashboard.monthly_report": "Monthly Report",
    "dashboard.no_data": "No Data",
    "dashboard.overview": "Overview",
    "dashboard.parent_portal": "Parent Portal",
    "dashboard.points": "Points",
    "dashboard.points_leaderboard": "Points Leaderboard",
    "dashboard.present": "Present",
    "dashboard.quick_actions": "Quick Actions",
    "dashboard.refund": "Refund",
    "dashboard.save": "Save",
    "dashboard.secondary": "Secondary",
    "dashboard.this_month's_birthdays": "This Month's Birthdays",
    "dashboard.today": "Today",
    "dashboard.total_expenses": "Total Expenses",
    "dashboard.total_income": "Total Income",
    "dashboard.total_students": "Total Students",
    "dashboard.total_teachers": "Total Teachers",
    "dashboard.unknown": "Unknown",
    "dashboard.view": "View",
    "dashboard.year_3": "Year 3",
    "dashboard.yesterday": "Yesterday",
    "education.april": "April",
    "education.august": "August",
    "education.cancelled": "Cancelled",
    "education.class": "Class",
    "education.completed": "Completed",
    "education.confirmed": "Confirmed",
    "education.course": "Course",
    "education.december": "December",
    "education.february": "February",
    "education.in_progress": "In Progress",
    "education.january": "January",
    "education.july": "July",
    "education.june": "June",
    "education.march": "March",
    "education.may": "May",
    "education.november": "November",
    "education.october": "October",
    "education.september": "September",
    "education.student": "Student",
    "education.teacher": "Teacher",
    "finance.account_number": "Account Number",
    "finance.actions": "Actions",
    "finance.active": "Active",
    "finance.all": "All",
    "finance.amount": "Amount",
    "finance.back": "Back",
    "finance.bank_account": "Bank Account",
    "finance.bank_name": "Bank Name",
    "finance.bank_reconciliation": "Bank Reconciliation",
    "finance.bank_transfer": "Bank Transfer",
    "finance.basic_info": "Basic Info",
    "finance.budget_management": "Budget Management",
    "finance.cancel": "Cancel",
    "finance.cancelled": "Cancelled",
    "finance.cash": "Cash",
    "finance.clear_selection": "Clear Selection",
    "finance.click_to_upload": "Click to Upload",
    "finance.completed": "Completed",
    "finance.confirm_delete": "Confirm Delete",
    "finance.date": "Date",
    "finance.default_settings": "Default Settings",
    "finance.delete_failed": "Delete Failed",
    "finance.deleted": "Deleted",
    "finance.description": "Description",
    "finance.disable": "Disable",
    "finance.disabled": "Disabled",
    "finance.draft": "Draft",
    "finance.edit": "Edit",
    "finance.email": "Email",
    "finance.enable": "Enable",
    "finance.expense": "Expense",
    "finance.expense_management": "Expense Management",
    "finance.failed": "Failed",
    "finance.fee_management": "Fee Management",
    "finance.finance_overview": "Finance Overview",
    "finance.financial_report": "Financial Report",
    "finance.grade": "Grade",
    "finance.import_failed": "Import Failed",
    "finance.income": "Income",
    "finance.invoice_management": "Invoice Management",
    "finance.invoice_no.": "Invoice No.",
    "finance.loading...": "Loading...",
    "finance.no_expense_records": "No expense records",
    "finance.no_payment_records": "No payment records",
    "finance.none": "None",
    "finance.normal": "Normal",
    "finance.notes": "Notes",
    "finance.other": "Other",
    "finance.overdue": "Overdue",
    "finance.paid": "Paid",
    "finance.payment_management": "Payment Management",
    "finance.payroll_management": "Payroll Management",
    "finance.pending": "Pending",
    "finance.pending_payment": "Pending Payment",
    "finance.phone": "Phone",
    "finance.primary": "Primary",
    "finance.processing": "Processing",
    "finance.receipt_list": "Receipt List",
    "finance.receipt_management": "Receipt Management",
    "finance.salary": "Salary",
    "finance.save": "Save",
    "finance.save_failed": "Save Failed",
    "finance.scheduled": "Scheduled",
    "finance.school_info": "School Info",
    "finance.search": "Search",
    "finance.secondary": "Secondary",
    "finance.select_all": "Select All",
    "finance.select_student": "Select Student",
    "finance.send_failed": "Send Failed",
    "finance.sent": "Sent",
    "finance.status": "Status",
    "finance.student": "Student",
    "finance.student_fees": "Student Fees",
    "finance.student_name": "Student Name",
    "finance.student_no.": "Student No.",
    "finance.system_normal": "System Normal",
    "finance.total": "Total",
    "finance.total_expenses": "Total Expenses",
    "finance.total_income": "Total Income",
    "finance.type": "Type",
    "finance.unknown": "Unknown",
    "finance.unknown_student": "Unknown Student",
    "finance.year_1": "Year 1",
    "finance.year_2": "Year 2",
    "finance.year_3": "Year 3",
    "finance.year_4": "Year 4",
    "finance.year_5": "Year 5",
    "finance.year_6": "Year 6",
    "grade.actions": "Actions",
    "grade.art": "Art",
    "grade.average_score": "Average Score",
    "grade.cancel": "Cancel",
    "grade.chinese": "Chinese",
    "grade.english": "English",
    "grade.geography": "Geography",
    "grade.grade": "Grade",
    "grade.grade_management": "Grade Management",
    "grade.highest_score": "Highest Score",
    "grade.history": "History",
    "grade.lowest_score": "Lowest Score",
    "grade.malay": "Malay",
    "grade.mathematics": "Mathematics",
    "grade.moral": "Moral",
    "grade.music": "Music",
    "grade.other": "Other",
    "grade.pass_rate": "Pass Rate",
    "grade.physical_education": "Physical Education",
    "grade.save": "Save",
    "grade.science": "Science",
    "grade.student": "Student",
    "grade.year": "Year",
    "homework.all_centers": "All Centers",
    "homework.all_grades": "All Grades",
    "homework.all_subjects": "All Subjects",
    "homework.art": "Art",
    "homework.center": "Center",
    "homework.chinese": "Chinese",
    "homework.english": "English",
    "homework.geography": "Geography",
    "homework.grade": "Grade",
    "homework.graded": "Graded",
    "homework.history": "History",
    "homework.homework_management": "Homework Management",
    "homework.load_failed": "Load Failed",
    "homework.loading...": "Loading...",
    "homework.mathematics": "Mathematics",
    "homework.moral": "Moral",
    "homework.music": "Music",
    "homework.not_submitted": "Not Submitted",
    "homework.other": "Other",
    "homework.physical_education": "Physical Education",
    "homework.save_failed": "Save Failed",
    "homework.saving...": "Saving...",
    "homework.science": "Science",
    "homework.select_subject": "Select Subject",
    "homework.select_teacher": "Select Teacher",
    "homework.subject": "Subject",
    "homework.submitted": "Submitted",
    "homework.year_1": "Year 1",
    "homework.year_2": "Year 2",
    "homework.year_3": "Year 3",
    "homework.year_4": "Year 4",
    "homework.year_5": "Year 5",
    "homework.year_6": "Year 6",
    "inventory.actions": "Actions",
    "inventory.all_status": "All Status",
    "inventory.cancel": "Cancel",
    "inventory.category": "Category",
    "inventory.description": "Description",
    "inventory.details": "Details",
    "inventory.inventory_management": "Inventory Management",
    "inventory.retry": "Retry",
    "inventory.save_failed": "Save Failed",
    "inventory.saving...": "Saving...",
    "inventory.status": "Status",
    "inventory.unit": "Unit",
    "parent.actions": "Actions",
    "parent.active": "Active",
    "parent.add": "Add",
    "parent.address": "Address",
    "parent.average_score": "Average Score",
    "parent.cancel": "Cancel",
    "parent.delete_failed": "Delete Failed",
    "parent.disabled": "Disabled",
    "parent.father": "Father",
    "parent.grades_query": "Grades Query",
    "parent.guardian": "Guardian",
    "parent.home_address": "Home Address",
    "parent.loading...": "Loading...",
    "parent.mother": "Mother",
    "parent.name": "Name",
    "parent.no_data": "No Data",
    "parent.notes": "Notes",
    "parent.other": "Other",
    "parent.overdue": "Overdue",
    "parent.paid": "Paid",
    "parent.parent_name": "Parent Name",
    "parent.pass_rate": "Pass Rate",
    "parent.payment_records": "Payment Records",
    "parent.pending_payment": "Pending Payment",
    "parent.phone": "Phone",
    "parent.relationship": "Relationship",
    "parent.save_failed": "Save Failed",
    "parent.saving...": "Saving...",
    "parent.status": "Status",
    "parent.unknown_student": "Unknown Student",
    "parent.update": "Update",
    "points.all": "All",
    "points.disabled": "Disabled",
    "points.enable": "Enable",
    "points.late": "Late",
    "points.loading...": "Loading...",
    "points.no_records": "No records",
    "points.operation_failed": "Operation Failed",
    "points.points": "Points",
    "points.points_rules": "Points Rules",
    "points.student": "Student",
    "points.teacher": "Teacher",
    "points.time": "Time",
    "points.unknown": "Unknown",
    "report.art": "Art",
    "report.average_score": "Average Score",
    "report.basic_info": "Basic Info",
    "report.cancel": "Cancel",
    "report.chinese": "Chinese",
    "report.click_to_upload": "Click to Upload",
    "report.custom": "Custom",
    "report.default_settings": "Default Settings",
    "report.email": "Email",
    "report.english": "English",
    "report.excellent": "Excellent",
    "report.geography": "Geography",
    "report.good": "Good",
    "report.history": "History",
    "report.june": "June",
    "report.malay": "Malay",
    "report.mathematics": "Mathematics",
    "report.moral": "Moral",
    "report.pass": "Pass",
    "report.phone": "Phone",
    "report.physical_education": "Physical Education",
    "report.save": "Save",
    "report.school_info": "School Info",
    "report.science": "Science",
    "report.subject": "Subject",
    "report.title": "Title",
    "report.year_4": "Year 4",
    "resource.system_normal": "System Normal",
    "student.": "",
    "student.actions": "Actions",
    "student.active_students": "Active Students",
    "student.add": "Add",
    "student.add_student": "Add Student",
    "student.advanced_filters": "Advanced Filters",
    "student.all": "All",
    "student.all_centers": "All Centers",
    "student.all_grades": "All Grades",
    "student.all_status": "All Status",
    "student.all_students": "All Students",
    "student.archived": "Archived",
    "student.art": "Art",
    "student.ascending": "Ascending",
    "student.basic_info": "Basic Info",
    "student.batch_delete": "Batch Delete",
    "student.cancel": "Cancel",
    "student.center": "Center",
    "student.chinese": "Chinese",
    "student.close": "Close",
    "student.contact_info": "Contact Info",
    "student.contact_phone": "Contact Phone",
    "student.created_at": "Created At",
    "student.data_load_failed": "Data Load Failed",
    "student.date_of_birth": "Date of Birth",
    "student.days": "days",
    "student.descending": "Descending",
    "student.draft": "Draft",
    "student.edit": "Edit",
    "student.edit_student": "Edit Student",
    "student.email": "Email",
    "student.email_address": "Email Address",
    "student.english": "English",
    "student.enrolled": "Enrolled",
    "student.father": "Father",
    "student.female": "Female",
    "student.form_1": "Form 1",
    "student.form_2": "Form 2",
    "student.form_3": "Form 3",
    "student.form_4": "Form 4",
    "student.form_5": "Form 5",
    "student.from": "From",
    "student.gender": "Gender",
    "student.geography": "Geography",
    "student.grade": "Grade",
    "student.graduated": "Graduated",
    "student.history": "History",
    "student.home_address": "Home Address",
    "student.inactive": "Inactive",
    "student.invalid_email_format": "Invalid email format",
    "student.left_school": "Left School",
    "student.level": "Level",
    "student.loading...": "Loading...",
    "student.malay": "Malay",
    "student.male": "Male",
    "student.mathematics": "Mathematics",
    "student.moral": "Moral",
    "student.mother": "Mother",
    "student.name": "Name",
    "student.no": "No",
    "student.no_student_data": "No student data",
    "student.none": "None",
    "student.not_set": "Not Set",
    "student.overdue": "Overdue",
    "student.paid": "Paid",
    "student.parent": "Parent",
    "student.pending_payment": "Pending Payment",
    "student.phone": "Phone",
    "student.physical_education": "Physical Education",
    "student.published": "Published",
    "student.quick_filters": "Quick Filters",
    "student.real_time_data": "Real-time Data",
    "student.relationship": "Relationship",
    "student.save_failed": "Save Failed",
    "student.saving...": "Saving...",
    "student.school": "School",
    "student.school_info": "School Info",
    "student.science": "Science",
    "student.select_date": "Select Date",
    "student.select_file": "Select File",
    "student.select_grade": "Select Grade",
    "student.semester": "Semester",
    "student.sort": "Sort",
    "student.status": "Status",
    "student.student": "Student",
    "student.student_details": "Student Details",
    "student.student_list": "Student List",
    "student.student_management": "Student Management",
    "student.student_name": "Student Name",
    "student.student_no.": "Student No.",
    "student.suspended": "Suspended",
    "student.system_normal": "System Normal",
    "student.total_students": "Total Students",
    "student.unknown": "Unknown",
    "student.unknown_error": "Unknown Error",
    "student.update": "Update",
    "student.update_failed": "Update Failed",
    "student.year": "Year",
    "student.year_1": "Year 1",
    "student.year_2": "Year 2",
    "student.year_3": "Year 3",
    "student.year_4": "Year 4",
    "student.year_5": "Year 5",
    "student.year_6": "Year 6",
    "student.yes": "Yes",
    "teacher.absent": "Absent",
    "teacher.account_number": "Account Number",
    "teacher.actions": "Actions",
    "teacher.active": "Active",
    "teacher.add": "Add",
    "teacher.add_teacher": "Add Teacher",
    "teacher.address": "Address",
    "teacher.advanced_filters": "Advanced Filters",
    "teacher.all_centers": "All Centers",
    "teacher.all_grades": "All Grades",
    "teacher.all_status": "All Status",
    "teacher.all_subjects": "All Subjects",
    "teacher.all_teachers": "All Teachers",
    "teacher.approved": "Approved",
    "teacher.archived": "Archived",
    "teacher.attendance_management": "Attendance Management",
    "teacher.attendance_rate": "Attendance Rate",
    "teacher.average": "Average",
    "teacher.bank_name": "Bank Name",
    "teacher.basic_info": "Basic Info",
    "teacher.batch_delete": "Batch Delete",
    "teacher.biology": "Biology",
    "teacher.cancel": "Cancel",
    "teacher.cancelled": "Cancelled",
    "teacher.center": "Center",
    "teacher.check_in_time": "Check-in Time",
    "teacher.check_out_time": "Check-out Time",
    "teacher.checked_in": "Checked In",
    "teacher.chemistry": "Chemistry",
    "teacher.chinese": "Chinese",
    "teacher.close": "Close",
    "teacher.collapse": "Collapse",
    "teacher.completed": "Completed",
    "teacher.confirmed": "Confirmed",
    "teacher.contact_info": "Contact Info",
    "teacher.contact_phone": "Contact Phone",
    "teacher.content": "Content",
    "teacher.create_failed": "Create Failed",
    "teacher.created_at": "Created At",
    "teacher.custom": "Custom",
    "teacher.dashboard": "Dashboard",
    "teacher.data_format_error": "Data format error",
    "teacher.date": "Date",
    "teacher.date_of_birth": "Date of Birth",
    "teacher.default_settings": "Default Settings",
    "teacher.delete_failed": "Delete Failed",
    "teacher.deleted_successfully": "Deleted Successfully",
    "teacher.draft": "Draft",
    "teacher.early_leave": "Early Leave",
    "teacher.edit_course": "Edit Course",
    "teacher.edit_teacher": "Edit Teacher",
    "teacher.eis": "EIS",
    "teacher.email": "Email",
    "teacher.emergency_contact": "Emergency Contact",
    "teacher.end_date": "End Date",
    "teacher.english": "English",
    "teacher.enrolled": "Enrolled",
    "teacher.enrollment_date": "Enrollment Date",
    "teacher.enter_address": "Enter Address",
    "teacher.enter_email": "Enter Email",
    "teacher.excellent": "Excellent",
    "teacher.expand": "Expand",
    "teacher.friday": "Friday",
    "teacher.generating...": "Generating...",
    "teacher.geography": "Geography",
    "teacher.good": "Good",
    "teacher.grade": "Grade",
    "teacher.graduated": "Graduated",
    "teacher.guardian": "Guardian",
    "teacher.history": "History",
    "teacher.homework": "Homework",
    "teacher.homework_management": "Homework Management",
    "teacher.in_progress": "In Progress",
    "teacher.inactive": "Inactive",
    "teacher.late": "Late",
    "teacher.leave": "Leave",
    "teacher.loading...": "Loading...",
    "teacher.lost": "Lost",
    "teacher.mathematics": "Mathematics",
    "teacher.monday": "Monday",
    "teacher.music": "Music",
    "teacher.name": "Name",
    "teacher.network_error": "Network Error",
    "teacher.no": "No",
    "teacher.none": "None",
    "teacher.normal": "Normal",
    "teacher.not_set": "Not Set",
    "teacher.notes": "Notes",
    "teacher.notification_center": "Notification Center",
    "teacher.notification_details": "Notification Details",
    "teacher.now": "Now",
    "teacher.operation_failed": "Operation Failed",
    "teacher.paid": "Paid",
    "teacher.paused": "Paused",
    "teacher.payroll_management": "Payroll Management",
    "teacher.pending_review": "Pending Review",
    "teacher.phone": "Phone",
    "teacher.physical_education": "Physical Education",
    "teacher.physics": "Physics",
    "teacher.points": "Points",
    "teacher.points_leaderboard": "Points Leaderboard",
    "teacher.present": "Present",
    "teacher.priority": "Priority",
    "teacher.quick_actions": "Quick Actions",
    "teacher.quick_filters": "Quick Filters",
    "teacher.read": "Read",
    "teacher.reject": "Reject",
    "teacher.rejected": "Rejected",
    "teacher.reload": "Reload",
    "teacher.resignation_date": "Resignation Date",
    "teacher.resigned": "Resigned",
    "teacher.reviewed": "Reviewed",
    "teacher.saturday": "Saturday",
    "teacher.science": "Science",
    "teacher.search": "Search",
    "teacher.search_students": "Search Students",
    "teacher.select_all": "Select All",
    "teacher.select_date": "Select Date",
    "teacher.select_file": "Select File",
    "teacher.select_student": "Select Student",
    "teacher.select_subject": "Select Subject",
    "teacher.select_teacher": "Select Teacher",
    "teacher.settings": "Settings",
    "teacher.sort_by": "Sort By",
    "teacher.start_date": "Start Date",
    "teacher.status": "Status",
    "teacher.student_check_in": "Student Check-in",
    "teacher.student_list": "Student List",
    "teacher.student_management": "Student Management",
    "teacher.subject": "Subject",
    "teacher.submitted": "Submitted",
    "teacher.submitting...": "Submitting...",
    "teacher.sunday": "Sunday",
    "teacher.system": "System",
    "teacher.system_normal": "System Normal",
    "teacher.system_notification": "System Notification",
    "teacher.teacher": "Teacher",
    "teacher.teacher_list": "Teacher List",
    "teacher.teacher_name": "Teacher Name",
    "teacher.thursday": "Thursday",
    "teacher.time_range": "Time Range",
    "teacher.timetable": "Timetable",
    "teacher.title": "Title",
    "teacher.today": "Today",
    "teacher.today's_classes": "Today's Classes",
    "teacher.total_courses": "Total Courses",
    "teacher.total_students": "Total Students",
    "teacher.total_teachers": "Total Teachers",
    "teacher.tuesday": "Tuesday",
    "teacher.type": "Type",
    "teacher.unknown": "Unknown",
    "teacher.unknown_error": "Unknown Error",
    "teacher.unknown_student": "Unknown Student",
    "teacher.unread": "Unread",
    "teacher.unread_notifications": "Unread Notifications",
    "teacher.update": "Update",
    "teacher.updated_at": "Updated At",
    "teacher.verified": "Verified",
    "teacher.vs_last_month": "vs Last Month",
    "teacher.wednesday": "Wednesday",
    "teacher.year": "Year",
    "teacher.year_3": "Year 3",
    "teacher.yes": "Yes",
    "tv.loading...": "Loading...",
    "tv.no_data": "No Data",
    "user.actions": "Actions",
    "user.admin": "Admin",
    "user.back_to_home": "Back to Home",
    "user.delete": "Delete",
    "user.email": "Email",
    "user.name": "Name",
    "user.no_users": "No users",
    "user.registration_time": "Registration Time",
    "user.role": "Role",
    "user.verify": "Verify",
},



    "admin.analyzing": "Analyzing...",
    "admin.registration_time": "Registration Time",
    "admin.this_week": "This Week",
    "admin.user_details": "User Details",
    "admin.yesterday": "Yesterday",
    "announcement.notification_center": "Notification Center",
    "announcement.notification_type": "Notification Type",
    "announcement.priority": "Priority",
    "announcement.system_notification": "System Notification",
    "announcement.time": "Time",
    "assignment.biology": "Biology",
    "assignment.chemistry": "Chemistry",
    "assignment.chinese": "Chinese",
    "assignment.completed": "Completed",
    "assignment.english": "English",
    "assignment.geography": "Geography",
    "assignment.graded": "Graded",
    "assignment.history": "History",
    "assignment.homework_list": "Homework List",
    "assignment.homework_title": "Homework Title",
    "assignment.in_progress": "In Progress",
    "assignment.mathematics": "Mathematics",
    "assignment.physics": "Physics",
    "assignment.science": "Science",
    "assignment.select_subject": "Select Subject",
    "assignment.submit_time": "Submit Time",
    "attendance.data_sync": "Data Sync",
    "attendance.phone": "Phone",
    "attendance.todays_attendance": "Today's Attendance",
    "card.all": "All",
    "card.card_list": "Card List",
    "card.delete": "Delete",
    "card.next": "Next",
    "card.previous": "Previous",
    "card.report_lost": "Report Lost",
    "center.disabled": "Disabled",
    "common.center_filter": "Center Filter",
    "communication.notification": "Notification",
    "course.advanced_filters": "Advanced Filters",
    "course.all_courses": "All Courses",
    "course.all_subjects": "All Subjects",
    "course.archived": "Archived",
    "course.class_name": "Class Name",
    "course.confirm_delete": "Confirm Delete",
    "course.count": "Count",
    "course.created_at": "Created At",
    "course.quick_filters": "Quick Filters",
    "course.scheduled": "Scheduled",
    "course.sort_by": "Sort By",
    "course.subject_filter": "Subject Filter",
    "exam.data_analysis": "Data Analysis",
    "exam.exam_name": "Exam Name",
    "exam.grade_distribution": "Grade Distribution",
    "exam.grade_management": "Grade Management",
    "exam.pass_rate": "Pass Rate",
    "exam.scheduled": "Scheduled",
    "exam.score": "Score",
    "exam.subject": "Subject",
    "finance.invoice_no": "Invoice No.",
    "finance.payment_records": "Payment Records",
    "inventory.back": "Back",
    "inventory.optional": "Optional",
    "inventory.quantity": "Quantity",
    "inventory.supplier": "Supplier",
    "inventory.unit_price": "Unit Price",
    "pickup.confirm": "Confirm",
    "pickup.pickup_management": "Pickup Management",
    "student.student_no": "Student No.",
    "system.auto_backup": "Auto Backup",
    "system.back_to_home": "Back to Home",
    "system.details": "Details",
    "system.system_settings": "System Settings",
    "system.user": "User",
    "teacher.generating": "Generating...",
    "teacher.loading": "Loading...",
    "teacher.todays_classes": "Today's Classes",
    "user.edit_user": "Edit User",
    "user.inactive": "Inactive",
    "user.search_users": "Search Users",
    "user.user_list": "User List",
    "user.user_management": "User Management",

    "admin.analyzing": "Analyzing...",
    "admin.registration_time": "Registration Time",
    "admin.this_week": "This Week",
    "admin.user_details": "User Details",
    "admin.yesterday": "Yesterday",
    "announcement.notification_center": "Notification Center",
    "announcement.notification_type": "Notification Type",
    "announcement.priority": "Priority",
    "announcement.system_notification": "System Notification",
    "announcement.time": "Time",
    "assignment.biology": "Biology",
    "assignment.chemistry": "Chemistry",
    "assignment.chinese": "Chinese",
    "assignment.completed": "Completed",
    "assignment.english": "English",
    "assignment.geography": "Geography",
    "assignment.graded": "Graded",
    "assignment.history": "History",
    "assignment.homework_list": "Homework List",
    "assignment.homework_title": "Homework Title",
    "assignment.in_progress": "In Progress",
    "assignment.mathematics": "Mathematics",
    "assignment.physics": "Physics",
    "assignment.science": "Science",
    "assignment.select_subject": "Select Subject",
    "assignment.submit_time": "Submit Time",
    "attendance.data_sync": "Data Sync",
    "attendance.phone": "Phone",
    "attendance.todays_attendance": "Today's Attendance",
    "card.all": "All",
    "card.card_list": "Card List",
    "card.delete": "Delete",
    "card.next": "Next",
    "card.previous": "Previous",
    "card.report_lost": "Report Lost",
    "center.disabled": "Disabled",
    "common.center_filter": "Center Filter",
    "communication.notification": "Notification",
    "course.advanced_filters": "Advanced Filters",
    "course.all_courses": "All Courses",
    "course.all_subjects": "All Subjects",
    "course.archived": "Archived",
    "course.class_name": "Class Name",
    "course.confirm_delete": "Confirm Delete",
    "course.count": "Count",
    "course.created_at": "Created At",
    "course.quick_filters": "Quick Filters",
    "course.scheduled": "Scheduled",
    "course.sort_by": "Sort By",
    "course.subject_filter": "Subject Filter",
    "exam.data_analysis": "Data Analysis",
    "exam.exam_name": "Exam Name",
    "exam.grade_distribution": "Grade Distribution",
    "exam.grade_management": "Grade Management",
    "exam.pass_rate": "Pass Rate",
    "exam.scheduled": "Scheduled",
    "exam.score": "Score",
    "exam.subject": "Subject",
    "finance.invoice_no": "Invoice No.",
    "finance.payment_records": "Payment Records",
    "inventory.back": "Back",
    "inventory.optional": "Optional",
    "inventory.quantity": "Quantity",
    "inventory.supplier": "Supplier",
    "inventory.unit_price": "Unit Price",
    "pickup.confirm": "Confirm",
    "pickup.pickup_management": "Pickup Management",
    "student.student_no": "Student No.",
    "system.auto_backup": "Auto Backup",
    "system.back_to_home": "Back to Home",
    "system.details": "Details",
    "system.system_settings": "System Settings",
    "system.user": "User",
    "teacher.generating": "Generating...",
    "teacher.loading": "Loading...",
    "teacher.todays_classes": "Today's Classes",
    "user.edit_user": "Edit User",
    "user.inactive": "Inactive",
    "user.search_users": "Search Users",
    "user.user_list": "User List",
    "user.user_management": "User Management",
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("zh")

  // Load from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem("pjpc_language") as Language
    if (saved && (saved === "zh" || saved === "en")) {
      setLanguage(saved)
    }
  }, [])

  // Save to localStorage on change
  useEffect(() => {
    localStorage.setItem("pjpc_language", language)
    // Update document lang
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en"
  }, [language])

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
