export const MOCK_STUDENTS = [
  {
    id: 'stu_1',
    student_name: 'Adrian Ng',
    student_id: 'WH-2024-001',
    standard: 'Primary 3',
    center: 'WX 01',
    status: 'active',
    parent_name: 'Mr. Ng',
    phone: '+60123456789',
    tuitionStatus: 'paid',
    cardNumber: 'NFC-998877',
    avatar: null,
  },
  {
    id: 'stu_2',
    student_name: 'Chloe Tan',
    student_id: 'WH-2024-002',
    standard: 'Primary 1',
    center: 'WX 02',
    status: 'active',
    parent_name: 'Ms. Tan',
    phone: '+60129876543',
    tuitionStatus: 'overdue',
    cardNumber: 'NFC-112233',
    avatar: null,
  },
  {
    id: 'stu_3',
    student_name: 'Jason Lim',
    student_id: 'WH-2024-003',
    standard: 'Secondary 1',
    center: 'WX 01',
    status: 'inactive',
    parent_name: 'Mr. Lim',
    phone: '+60125554433',
    tuitionStatus: 'partial',
    cardNumber: 'NFC-445566',
    avatar: null,
  },
];

export const MOCK_FEES = [
  {
    id: 'fee_1',
    name: 'Monthly Tuition Fee',
    category: 'Academic',
    amount: 150,
    type: 'recurring',
    applicableGrades: ['Primary 1', 'Primary 2', 'Primary 3'],
    status: 'active',
  },
  {
    id: 'fee_2',
    name: 'Registration Fee',
    category: 'Admin',
    amount: 50,
    type: 'one-time',
    applicableGrades: ['All'],
    status: 'active',
  },
];

export const MOCK_INVOICES = [
  {
    id: 'inv_1',
    invoiceNumber: 'INV-2024-001',
    studentId: 'stu_1',
    studentName: 'Adrian Ng',
    totalAmount: 200,
    status: 'paid',
    issueDate: '2024-05-01',
    dueDate: '2024-05-15',
  },
  {
    id: 'inv_2',
    invoiceNumber: 'INV-2024-002',
    studentId: 'stu_2',
    studentName: 'Chloe Tan',
    totalAmount: 150,
    status: 'overdue',
    issueDate: '2024-05-01',
    dueDate: '2024-05-15',
  },
];
