import jsPDF from "jspdf"
import "jspdf-autotable"
import { Invoice } from '@/hooks/useInvoices'

export interface PDFOptions {
  schoolName: string
  schoolLogo?: string
  schoolAddress: string
  schoolPhone: string
  schoolEmail: string
  taxNumber: string
}

// Status helpers
const getStatusText = (status: string): string => {
  const map: Record<string,string> = {draft:'草稿',issued:'已开具',sent:'已发送',pending:'待付款',overdue:'已逾期',paid:'已付款',cancelled:'已取消'}
  return map[status] || status
}

export const generateInvoicePDF = async (invoice: Invoice, options: PDFOptions): Promise<Blob> => {
  const doc = new jsPDF()
  const pageW = doc.internal.pageSize.getWidth()

  // ── Header / School Info ──
  doc.setFontSize(20)
  doc.setTextColor(79, 70, 229)
  doc.text(options.schoolName, pageW / 2, 20, { align: "center" })
  doc.setFontSize(9)
  doc.setTextColor(100)
  doc.text(options.schoolAddress, pageW / 2, 27, { align: "center" })
  doc.text(`Tel: ${options.schoolPhone}  |  Email: ${options.schoolEmail}`, pageW / 2, 32, { align: "center" })
  doc.text(`Tax No: ${options.taxNumber}`, pageW / 2, 37, { align: "center" })

  doc.setDrawColor(200)
  doc.line(14, 42, pageW - 14, 42)

  // ── Invoice Info ──
  doc.setFontSize(16)
  doc.setTextColor(51)
  doc.text(`Invoice #${invoice.invoiceNumber}`, 14, 52)
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text(`Issue: ${invoice.issueDate}`, 14, 59)
  doc.text(`Due: ${invoice.dueDate}`, 14, 65)
  doc.text(`Student: ${invoice.studentName}`, 14, 71)
  doc.text(`Status: ${getStatusText(invoice.status)}`, 14, 77)

  // ── Items Table ──
  const tableRows = (invoice.items || []).map((item: any) => [
    item.name || item.description || "—",
    `RM ${(item.amount || 0).toFixed(2)}`
  ])
  if (tableRows.length > 0) {
    (doc as any).autoTable({
      startY: 85,
      head: [["Item", "Amount (RM)"]],
      body: tableRows,
      theme: "grid",
      headStyles: { fillColor: [79, 70, 229], textColor: 255 },
      styles: { font: "helvetica", fontSize: 10 },
      columnStyles: { 1: { halign: "right" } },
    })
  }

  const finalY = (doc as any).lastAutoTable?.finalY || 85

  // ── Total ──
  doc.setFontSize(14)
  doc.setTextColor(51)
  doc.text(`Total: RM ${(invoice.totalAmount || 0).toFixed(2)}`, pageW - 14, finalY + 12, { align: "right" })

  // ── Notes ──
  if (invoice.notes) {
    doc.setFontSize(9)
    doc.setTextColor(100)
    doc.text(`Notes: ${invoice.notes}`, 14, finalY + 25)
  }

  // ── Footer ──
  const footerY = doc.internal.pageSize.getHeight() - 15
  doc.setDrawColor(200)
  doc.line(14, footerY - 5, pageW - 14, footerY - 5)
  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text(`Thank you for choosing ${options.schoolName}.`, pageW / 2, footerY, { align: "center" })
  doc.text("This invoice is auto-generated by the system.", pageW / 2, footerY + 5, { align: "center" })

  return doc.output("blob")
}

export const downloadInvoicePDF = async (invoice: Invoice, options: PDFOptions): Promise<void> => {
  try {
    const blob = await generateInvoicePDF(invoice, options)
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `Invoice_${invoice.invoiceNumber}.pdf`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  } catch (error) {
    console.error('PDF generation failed:', error)
    throw new Error('PDF generation failed')
  }
}

export const printInvoicePDF = async (invoice: Invoice, options: PDFOptions): Promise<void> => {
  try {
    const blob = await generateInvoicePDF(invoice, options)
    const url = URL.createObjectURL(blob)
    const printWindow = window.open(url, '_blank')
    if (printWindow) {
      printWindow.onload = () => {
        printWindow.print()
        setTimeout(() => { printWindow.close(); URL.revokeObjectURL(url) }, 1000)
      }
    }
  } catch (error) {
    console.error('PDF printing failed:', error)
    throw new Error('PDF printing failed')
  }
}
